### ISSUE TITLE
Problems apply to real camera

### ISSUE THREAD

**Issue by MyungHaSong** [j96w/DenseFusion#102]
first of all thank you for sharing code
I am testing densefusion for the robot. but the test dataset provided showed excellent results, but I found that the pose estimation using my real camera was not good.

The photo below shows the results of applying the test dataset.
![1007](https://user-images.githubusercontent.com/28686925/67372813-727c1480-f5b9-11e9-904d-55c17e516576.png)

The picture below shows the test results in a real environment.
<img width="797" alt="git" src="https://user-images.githubusercontent.com/28686925/67373012-d272bb00-f5b9-11e9-8561-ebcbd4807b43.PNG">

Photo 1 is the segmentation result, photo 2 is the rgb input image, photo 3 is the depth input image. Photo 4 shows the result of the pose estimation.

And the pose value for photo 4 is 
qx = -0.19133821, qy = -0.43451482, qz = -0.79248542, qw = 0.38282296
tx = 0.0020432957, ty = -0.0020210464, tz = 0.075942591

Can you help me what is the problem?

**Comment by khmariem** [comment]
I think it has to be a problem with calibration. The code specifies fx, fy, cx and cy for a certain camera. So, I believe you should adjust this to the one you use.

**Comment by MyungHaSong** [comment]
@khmariem Thank you for your reply.

the first thing, camera calibration was performed as advised.
my camera is a realsense d435 and the calibration result is 
cam matrix = [[611.74987678,          0,            327.95667082],
                       [0,             612.30238416,            243.9433155],
                       [0,                              0 ,                             1]
dist = [0.04257707, 0.27646419, -0.005677465, -0.00646358,
          -1.27944517,-0.0463144,-0.27004919,1.31856356, 
            0 , 0 , 0 , 0 ,0 , 0]

The result of applying this value is shown below.
<img width="685" alt="git2" src="https://user-images.githubusercontent.com/28686925/67449725-12877b80-f656-11e9-9265-9c807500d669.PNG">

**Comment by j96w** [comment]
Hi, please double check your depth scale. It is named as `cam_scale` in the code. Try different scale to see whether it works.

**Comment by MyungHaSong** [comment]
Thanks for the advice.

As you advised, I have changed cam scale from 10000.0 to 1000.0 
The result of applying this value is shown below.

<img width="705" alt="git3" src="https://user-images.githubusercontent.com/28686925/67460671-8fc2e880-f676-11e9-9110-62bac6fd9e6a.PNG">

**Comment by j96w** [comment]
Seems like still not the same scale? How about comparing the scale of the object model with the pointcloud generated from the depth? Or maybe you can run ICP to see whether the model can fit the depth.

**Comment by j96w** [comment]
Any updates?

**Comment by TONG369** [comment]
> Thanks for the advice.
> As you advised, I have changed cam scale from 10000.0 to 1000.0
> The result of applying this value is shown below.

Hello, excuse me ~ ask you a question, how do you do the visualization of the experimental results? In other words, how do you achieve the experimental results displayed on the webpage? Do you have references or links? If so, please send me a copy. If not, can you give me a reminder? Thanks for your guidance. Looking forward to your reply.

**Comment by huckl3b3rry87** [comment]
@MyungHaSong looks like you did a ros implemetnation, but it looks like you did not make a fork, can you please provide the code for this? 

It would help https://github.com/j96w/DenseFusion/issues/6

**Comment by MyungHaSong** [comment]
I'm cleaning up code made with ROS, and I'll put it up when it's cleaned up.

**Comment by ROSNovice** [comment]
@MyungHaSong i am looking forward your ROS implementation

**Comment by kkkniu** [comment]
@MyungHaSong Hello, how many photos of training can achieve such an effect as yours?
