### ISSUE TITLE
Evaluate own dataset

### ISSUE THREAD

**Issue by marmas92** [j96w/DenseFusion#103]
Hey, thanks for sharing your code!!
I am able to train my own dataset, which has the format of the linemod dataset. Could someone please tell me how to evaluate my own dataset and visualize the results?
Thank you very much in advance!!

**Comment by j96w** [comment]
Hi, do you have the ground truth label of your own dataset? If you have, a simpler way is just to calculate the rotation error and translation error. If you also have the object mesh models, then you can do ADD error as linemod and YCB dataset did.

**Comment by marmas92** [comment]
Thank you for the respond!
Yes I have the ground trouth label and the object mesh models. The problem is, that I dont know which script/command I need to run. Or do I need to write my own script for evaluation? Also how do I visualize the results - do I need this https://github.com/knorth55/chainer-dense-fusion? Sorry if these are stupid questions, but I am very new to the whole topic.

**Comment by j96w** [comment]
Hi, it would be better if you could write your evaluation. Basically, you only need to calculate the rotation error (the angle between your predicted rotation and GT rotation) and the translation error (distance between your predicted trans to GT trans). The visualization can be acquired by projecting each point of the object mesh (transformed by your predicted pose) to the image plane by using the camera matrix. It would be great if you could take a fraction of time to understand these steps.

**Comment by marmas92** [comment]
Thank you very much for the input!

**Comment by chengm0-0** [comment]
> 嘿，谢谢你分享你的代码！
> 我能够训练自己的数据集，该数据集具有linemod数据集的格式。有人可以告诉我如何评估自己的数据集并可视化结果吗？
> 提前非常感谢您！！

Hi. how did you create your dataset?
