### ISSUE TITLE
End-to-end training including the segmentation?

### ISSUE THREAD

**Issue by sklee2014** [j96w/DenseFusion#106]
First of all thanks for sharing great results and codes.
It seems that semantic segmentation is trained separately to the main 6d pose estimation algorithm.
Would it be also possible to train the whole processes end-to-end? (Or would it be meaningful?)

**Comment by yjdfly** [comment]
when I lower the batch size from 3 to1 and use "with torch.no_grad():" before "...=model(rgb)"，the error"CUDA out of memory" is solved，but the other error "element 0 of tenseor ..."appears at "....forward"，detailed errors are posted at the top.I can't solve it ,hope you can tell me why.Thanks a lot.

**Comment by akeaveny** [comment]
Hi @sklee2014, did you ever try integrating a mask branch to DenseFusion?

I'm currently using MaskRCNN for segmentation but it would be interesting to see preformance gains with end-to-end training.
