### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ldepn** [j96w/DenseFusion#110]
error in knn: invalid device function
Traceback (most recent call last):
  File "/home/amax/code/DenseFusion-Pytorch-1.0/tools/train.py", line 242, in <module>
    main()
  File "/home/amax/code/DenseFusion-Pytorch-1.0/tools/train.py", line 145, in main
    loss, dis, new_points, new_target = criterion(pred_r, pred_t, pred_c, target, model_points, idx, points, opt.w, opt.refine_start)
  File "/home/amax/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/amax/code/DenseFusion-Pytorch-1.0/lib/loss.py", line 83, in forward
    return loss_calculation(pred_r, pred_t, pred_c, target, model_points, idx, points, w, refine, self.num_pt_mesh, self.sym_list)
  File "/home/amax/code/DenseFusion-Pytorch-1.0/lib/loss.py", line 44, in loss_calculation
    inds = knn(target.unsqueeze(0), pred.unsqueeze(0))
  File "/home/amax/code/DenseFusion-Pytorch-1.0/lib/knn/__init__.py", line 21, in forward
    knn_pytorch.knn(ref, query, inds)
RuntimeError: aborting at /home/amax/code/DenseFusion-Pytorch-1.0/lib/knn/src/knn.h:45

**Comment by j96w** [comment]
Hi, how about build a new Pytorch 0.4.1 environment and use my code to see whether still has this issue?

**Comment by ldepn** [comment]
I debug find the bug in this 
    if not refine:
        if idx[0].item() in sym_list:
            target = target[0].transpose(1, 0).contiguous().view(3, -1)
            pred = pred.permute(2, 0, 1).contiguous().view(3, -1)
            **inds = knn(target.unsqueeze(0), pred.unsqueeze(0))**
            target = torch.index_select(target, 1, inds.view(-1).detach() - 1)
            target = target.view(3, bs * num_p, num_point_mesh).permute(1, 2, 0).contiguous()
            pred = pred.view(3, bs * num_p, num_point_mesh).permute(1, 2, 0).contiguous()“
”

**Comment by j96w** [comment]
ok, I didn't have this problem before. Any updates?

**Comment by ldepn** [comment]
when i use Pytorch 0.4.1, show the bug “AttributeError: module 'torchvision.transforms' has no attribute 'ColorJitter'”
my torchvision version is 0.1.8，pytorch version is 0.4.1 cuda =9.0

**Comment by ldepn** [comment]
when i want to install torchvision = 0.3.0，
 
UnsatisfiableError: The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (pytorch):

  - torchvision=0.3.0 -> pytorch=1.1

**Comment by RobbyHuang** [comment]
@ldepn Hi，I met the same problem ,do you know how to deal with it ?

**Comment by MengHao666** [comment]
> when i use Pytorch 0.4.1, show the bug “AttributeError: module 'torchvision.transforms' has no attribute 'ColorJitter'”
> my torchvision version is 0.1.8，pytorch version is 0.4.1 cuda =9.0

have u solved this problem?
