### ISSUE TITLE
Cannot download YCB_Video_Dataset.

### ISSUE THREAD

**Issue by kroglice** [j96w/DenseFusion#111]
The link provided to the ycb does not work.
This YCB is the normal one? or it also has the masks of the objects like the preprocessed Linemod provided?

Thank you in advance.

**Comment by j96w** [comment]
Hi, yes, the YCB is the normal one provided by PoseCNN and nothing additional is required. It seems like the link works well on my side.

**Comment by kroglice** [comment]
Thank You.
