### ISSUE TITLE
when I run vanilla_segmentation "train..py" appears "RuntimeError: element 0 of tensors”

### ISSUE THREAD

**Issue by yjdfly** [j96w/DenseFusion#112]
When I run “vanilla_segmentation/train.py” directly, an error occurs “RuntimeError: CUDA error: out of memory”. So I lower the batch size from 3 to1 and use "with torch.no_grad():" before "semantic =model(rgb)"，the error"CUDA out of memory" is solved，but the other error "RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn" appears at "semantic_loss.backward()"，detailed errors are posted as follows. I can't solve it ,hope you can tell me why. Thanks a lot!!!

**Comment by j96w** [comment]
Hi, could you double check whether `requires_grad` of the Variable is set to True?

**Comment by yjdfly** [comment]
I realized that I didn't really solve the problem "RuntimeError: CUDA error: out of memory"  even though I lower the batch size from 3 to1. Is it because my poor GPU memory? I use GTX 1060 (3GB),can you give me some advice?thanks.

**Comment by yjdfly** [comment]
> Hi, could you double check whether `requires_grad` of the Variable is set to True?

I realized that I didn't really solve the problem "RuntimeError: CUDA error: out of memory" even though I lower the batch size from 3 to1. Is it because my poor GPU memory? I use GTX 1060 (3GB),can you give me some advice?thanks.

**Comment by j96w** [comment]
Hi, 3GB is not enough for training. Take a try with 6~8GB GPU.

**Comment by yjdfly** [comment]
It's true that the GPU memory is too small. I succeeded on a larger platform. Thank you for your patience
