### ISSUE TITLE
Dimension mismatch

### ISSUE THREAD

**Issue by vijaysamula** [j96w/DenseFusion#114]
![refine_error](https://user-images.githubusercontent.com/50096409/68117918-f5c53080-fefe-11e9-8d70-c3b3bcd89f93.png)
Hi guys,
I am testing the YCB dataset with ROS. I have encountered the following error when I tried to test. The error is in PoseRineNet size mismatch for feat.conv5.weight: copying a param of torch.
**RuntimeError: Error(s) in loading state_dict for PoseRefineNet:**
**Size([512, 384, 1]) from the checkpoint, where the shape is torch.Size([512, 256, 1]) in current model**.
	**size mismatch for conv1_r.bias: copying a param of torch.Size([512]) from checkpoint, where the shape is torch.Size([640]) in current model.
	size mismatch for conv1_r.weight: copying a param of torch.Size([512, 1024]) from checkpoint, where the shape is torch.Size([640, 1408, 1]) in current model.
	size mismatch for conv1_t.bias: copying a param of torch.Size([512]) from checkpoint, where the shape is torch.Size([640]) in current model.
	size mismatch for conv1_t.weight: copying a param of torch.Size([512, 1024]) from checkpoint, where the shape is torch.Size([640, 1408, 1]) in current model.
	size mismatch for conv2_r.bias: copying a param of torch.Size([128]) from checkpoint, where the shape is torch.Size([256]) in current model.
	size mismatch for conv2_r.weight: copying a param of torch.Size([128, 512]) from checkpoint, where the shape is torch.Size([256, 640, 1]) in current model.
	size mismatch for conv2_t.bias: copying a param of torch.Size([128]) from checkpoint, where the shape is torch.Size([256]) in current model.
	size mismatch for conv2_t.weight: copying a param of torch.Size([128, 512]) from checkpoint, where the shape is torch.Size([256, 640, 1]) in current model.
	size mismatch for conv3_r.bias: copying a param of torch.Size([84]) from checkpoint, where the shape is torch.Size([128]) in current model.
	size mismatch for conv3_r.weight: copying a param of torch.Size([84, 128]) from checkpoint, where the shape is torch.Size([128, 256, 1]) in current model.
	size mismatch for conv3_t.bias: copying a param of torch.Size([63]) from checkpoint, where the shape is torch.Size([128]) in current model.
	size mismatch for conv3_t.weight: copying a param of torch.Size([63, 128]) from checkpoint, where the shape is torch.Size([128, 256, 1]) in current model.**

Help me in resolving this error.

**Comment by j96w** [comment]
Hi, did you change the code in the `network.py`? Could you take a try with the original one?

**Comment by vijaysamula** [comment]
No, I didn't change the code in network.py. I have tried with both pytorch=0.4.1 and pytorch=1.0.0.
Though the error is same

**Comment by j96w** [comment]
But, as we can see, it is obvious a weight loading problem. Could you double check whether you are trying to load the refinement weight into the main model (or reverse of it)? There are two parts in DenseFusion.

**Comment by vijaysamula** [comment]
I have checked a lot of times also tried in docker image and different virtual environments.

**Comment by vijaysamula** [comment]
Hi,
I have checked in another pc with RTX 1080 Ti graphics card, there is no error. But when I tried in pc with GTX 2080 and GTX 1060. I am getting the following error(mentioned above).

**Comment by j96w** [comment]
Thanks for your hard work. So the problem is because of the GPU (even with the same code)? Interesting finding.

**Comment by vijaysamula** [comment]
Yes, with the same code

**Comment by j96w** [comment]
So it might not be a good conclusion for this issue. Feel free to reopen it if anyone finds the same problem.
