### ISSUE TITLE
Have you tried multi-same object?

### ISSUE THREAD

**Issue by YanqingWu** [j96w/DenseFusion#116]
Can you recommend a network? Maybe mask-rcnn or anything else?

**Comment by j96w** [comment]
Hi, sorry, could you remind me what multi-same object is?

**Comment by YanqingWu** [comment]
> Hi, sorry, could you remind me what multi-same object is?

For example I have 10 apples in one image, so we need instance segmentation to 
distinguish them. Segnet will classify them as one class, we cannot get the mask for each of them. So I want to know have tried something in this scene.

**Comment by j96w** [comment]
I see. Take a try with MaskRCNN. It should work quite well.
