### ISSUE TITLE
Legacy autograd function with non-static forward method is deprecated 

### ISSUE THREAD

**Issue by marmas92** [j96w/DenseFusion#118]
Hey there, 
so far everything worked, but I tried to train with a new object. To be able to train with that object I have to set "num_pt_mesh_small = 300". But now every iteration I get the message "Legacy autograd function with non-static forward method is deprecated and will be removed in 1.3. Please use new-style autograd function with static forward method.". 
Does anyone has an idea how to fix this?

**Comment by drapado** [comment]
@marmas92 did you manage to solve it? I'm trying to run densefusion in pytorch 1.6 and I'm facing the same error

**Comment by saicharanb56** [comment]
Hi. Has anyone been able to solve this issue?

I get this same error for the forward method used in line 83 of loss.py.
