### ISSUE TITLE
KNN segmentation fault

### ISSUE THREAD

**Issue by Guptajakala** [j96w/DenseFusion#12]
When I try to train on LINEMOD, I met this:
> ./experiments/scripts/train_linemod.sh: line 10: 10128 Segmentation fault      python3 ./tools/train.py --dataset linemod --dataset_root ./datasets/linemod/Linemod_preprocessed

I have verified that it happens at [this line
](https://github.com/j96w/DenseFusion/blob/dd8ff1a4d67faac1149e378045135b45b6f810f1/lib/loss.py#L44)

Could you point me to any solutions? Thanks!

**Comment by j96w** [comment]
Make sure you are using the correct version of Pytorch.

**Comment by Guptajakala** [comment]
It works not when I use exactly 0.4.1
Thanks!
