### ISSUE TITLE
Issue with comparing gt to predicted gt

### ISSUE THREAD

**Issue by marmas92** [j96w/DenseFusion#121]
Thank you again for sharing your code!
I am training your network with synthetic generated data. Therefore I do the following - I have a fix camera looking at a scene where I generate objects with a random pose.  Now I write data in the form of the linemod dataset but instead of the camera rotation and translation as  "cam_R_m2c" and  "cam_t_m2c" I write down the translation and rotation of the regarding object. 

The network now is training and I am getting an average distance of around 0.0105252 (whats ok I think). But when I print out the predicted rotation and translation I get totally wrong values compared to the groundtrouth of my objects (see screanshot). 
I think this is because I give the network the rotation and translation of the objects and not the camera. Do I need to change my data generation or is there a simple calulation step at the end so I get the right prediction of the rotation and translation? I hope thats not a stupid question ^^
Thanks in advance!
![printout_gt](https://user-images.githubusercontent.com/51153981/68743681-41f52c80-05f3-11ea-92dc-b1689be54e17.jpeg)

**Comment by j96w** [comment]
Hi, it would be better if you could spend some time to find a more academic answer from other resources. Basically, you need to make sure that the GT pose is corresponding to the camera frame.

**Comment by cwczyj** [comment]
@marmas92 sorry, I met the same error, could you tell me how do you correct this? Thanks!

**Comment by Ixion46** [comment]
Hey @marmas92 ,
I hope you still read that. I have kinda the same issues as you had. My predicted translation is close to the gt-translation, but the predicted rotation is totaly off. Were you able to fix that problem and can you maybe help me?

**Comment by Ixion46** [comment]
Hey @marmas92 ,
can you please help me? I am really stuck at this problem for a long time now. Would be really thankful.
Best regards Ixion
