### ISSUE TITLE
The link of download trained_checkpoints is invalided

### ISSUE THREAD

**Issue by 50618861** [j96w/DenseFusion#125]
Hi

The link of download trained_checkpoints is invalided, can you update it?

Thanks

**Comment by j96w** [comment]
Hi, it works well on my side.

**Comment by 50618861** [comment]
The link https://docs.google.com/uc?export=download&id=1bQ9H-fyZplQoNt1qRwdIUX5_3_1pj6US doesn't work for me. Could you send the trained_checkpoints.zip for me through the gmail or google-drive?

**Comment by j96w** [comment]
Hi, sorry but your link is not the one I shared in this code repo. How about this one: https://drive.google.com/drive/folders/19ivHpaKm9dOrr12fzC8IDFczWRPFxho7

**Comment by 50618861** [comment]
Thanks for your help.
