### ISSUE TITLE
Test on the Occluded-LINEMOD dataset

### ISSUE THREAD

**Issue by sunshantong** [j96w/DenseFusion#126]
Hi, Sorry to bother you again. Is it possible to test on the Occluded-LINEMOD dataset? My idea is to use your vanilla SegNet for segmentation. Since all the objects in the scene need to be segmented, and the objects are blocked seriously. This will leads to a failure to get a completed mask. So is that feasible?  Or is there another way?
Thank you in advance.

**Comment by WW-0** [comment]
> Hi, Sorry to bother you again. Is it possible to test on the Occluded-LINEMOD dataset? My idea is to use your vanilla SegNet for segmentation. Since all the objects in the scene need to be segmented, and the objects are blocked seriously. This will leads to a failure to get a completed mask. So is that feasible? Or is there another way?
> Thank you in advance.

Have you solved the problem？

**Comment by sunshantong** [comment]
> > Hi, Sorry to bother you again. Is it possible to test on the Occluded-LINEMOD dataset? My idea is to use your vanilla SegNet for segmentation. Since all the objects in the scene need to be segmented, and the objects are blocked seriously. This will leads to a failure to get a completed mask. So is that feasible? Or is there another way?
> > Thank you in advance.
> 
> Have you solved the problem？

Sorry, I have not resolved it.

**Comment by Chu1Wan9** [comment]
Hello, have you completed the testing on Occluded-LineMod? I don't know how to load the Occluded-LineMod dataset in bop format. I wrote a datasetlmo.py file, but it won't run.
