### ISSUE TITLE
Evaluation on LineMod dataset ValueError: Traceback (most recent call last)

### ISSUE THREAD

**Issue by lalaLin997** [j96w/DenseFusion#127]
Sorrt to bother you.
When I run eval_linemod.sh, I got the error like below:
+ set -e
+ export PYTHONUNBUFFERED=True
+ PYTHONUNBUFFERED=True
+ export CUDA_VISIBLE_DEVICES=0
+ CUDA_VISIBLE_DEVICES=0
+ python3 /home/fah/DenseFusion/tools/eval_linemod.py --dataset_root  /home/fah//DenseFusion/datasets/linemod/Linemod_preprocessed --model  /home/fah//DenseFusion/trained_checkpoints/linemod/pose_model_9_0.01310166542980859.pth --refine_model  /home/fah//DenseFusion/trained_checkpoints/linemod/pose_refine_model_493_0.006761023565178073.pth
 /home/fah//DenseFusion/lib/transformations.py:1912: UserWarning: failed to import module _transformations
  warnings.warn('failed to import module %s' % name)
Object 1 buffer loaded
Object 2 buffer loaded
Object 4 buffer loaded
Object 5 buffer loaded
Object 6 buffer loaded
Object 8 buffer loaded
Object 9 buffer loaded
Object 10 buffer loaded
Object 11 buffer loaded
Object 12 buffer loaded
Object 13 buffer loaded
Object 14 buffer loaded
Object 15 buffer loaded
/usr/local/lib/python3.5/dist-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='elementwise_mean' instead.
  warnings.warn(warning.format(ret))
[0.010209865663, 0.024750624233, 0.017249224865, 0.020140358597000002, 0.015454551808, 0.026147178102, 0.010899920102000001, 0.016462758847999998, 0.017588933422000002, 0.014554287471000002, 0.027807811733, 0.028260129399, 0.021235825148]
Traceback (most recent call last):
  File " /home/fah//DenseFusion/tools/eval_linemod.py", line 68, in <module>
    for i, data in enumerate(testdataloader, 0):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File " /home/fah//DenseFusion/datasets/linemod/dataset.py", line 122, in __getitem__
    rmin, rmax, cmin, cmax = get_bbox(mask_to_bbox(mask_label))
  File " /home/fah//DenseFusion/datasets/linemod/dataset.py", line 218, in mask_to_bbox
    _, contours, _ = cv2.findContours(mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

-----------------------------------------------------------------------------------------------------------
it's seems the pytorch error or not? I install PyTorch 0.4.1 .
Can you teach me how to solve this problem?
Thank you in advance.

**Comment by firstdeep** [comment]
same problem

**Comment by firstdeep** [comment]
> same problem

I solved this problem, 

_, contours, _ = cv2.findContours(mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

Change it to:
contours, _ = cv2.findContours(mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

Restart the kernel and run. Your problem should be fixed

**Comment by lalaLin997** [comment]
@firstdeep it's work, thanks a lot!

**Comment by huckl3b3rry87** [comment]
This is still an issue and should be reopened until the fix is merged

**Comment by huckl3b3rry87** [comment]
fixed with https://github.com/j96w/DenseFusion/pulls

**Comment by j96w** [comment]
Thanks @huckl3b3rry87's PR to fix this issue.
