### ISSUE TITLE
PoseNet(No refine) model evaluate result does not match

### ISSUE THREAD

**Issue by gmengusthk** [j96w/DenseFusion#13]
On linemod dataset, we evaluated the model provided (trained_models/linemod/pose_model_9_0.01310166542980859.pth) without refinement and the success rate is 0.83169, which does not match what is claimed in the the paper (per-pixel: 86.2). Is the provided PoseNet model used to evaluate the per-pixel performance? If not, could you please provide the model used to evaluate the per-pixel performance?
Thank you!

**Comment by j96w** [comment]
A no refine checkpoint (per-pixel: 86.6) has been uploaded to the zip file, named 'no_refine_pose_model_15_0.011377632944034037.pth'. If you want to train to get this result by yourself, the only thing you need to do is close the pose refinement process and wait for about 10 more epochs. The best performance you can have is close to per-pixel:87 but it's far inferior to iterative:94.3.

**Comment by hoangcuongbk80** [comment]
@j96w Thanks for your work!
Could you please provide the trained model for YCB video dataset? I have trained on my computer for 3 days, but the results is still not good.

**Comment by j96w** [comment]
Please follow the readme of this repo to download the trained_checkpoints.zip, which already contains a no_refine_model(per-pixel AUC:91.2) and a refine_model(iterative AUC:93.2) that match the result we reported in the paper. Also, make sure you are correctly using the code, cuz we have tested a couple of times before our release and all of them can reach or even slightly better than the reported result.

**Comment by hoangcuongbk80** [comment]
I found it. Thank you very much!

**Comment by WW-0** [comment]
On linemod dataset, how do you evaluate  the model provided without refinement? It reports an error when I use the following command: 
```
python ./tools/eval_linemod.py --dataset_root ./datasets/linemod/Linemod_preprocessed --model pose_model_current.pth
```
I'm not using the parameter "--refine_model ". The error means that I lack the refine_model file. So I don't know what the right command is
