### ISSUE TITLE
Segnet outputs mask even though there is no object in frames

### ISSUE THREAD

**Issue by TrinhTUHH** [j96w/DenseFusion#130]
Hi,
I trained SegNet on my own dataset, and it worked well if the input frames including target object. But when there are no objects in frames, SegNet still outputs masked pixels. Does anyone know how to avoid this? I also tried Unet but same things happened.

**Comment by j96w** [comment]
Hi, could you double check whether your segnet has a 0-channel for the background. If so, you should not have this issue.
