### ISSUE TITLE
Missing folder when evaluate on YCB_Video Dataset

### ISSUE THREAD

**Issue by staceycy** [j96w/DenseFusion#14]
Hi Jeremy,

I tried to run the evaluation on YCB dataset with your matlab codes. 
It shows missing folder called 'results_3DCoordinate' coming from the code below:
https://github.com/j96w/DenseFusion/blob/dd8ff1a4d67faac1149e378045135b45b6f810f1/replace_ycb_toolbox/evaluate_poses_keyframe.m#L55
Could you please tell what this folder contains? 

Thank you. 
Regards,
Stacey

**Comment by j96w** [comment]
You can find this folder in the result_PoseCNN.zip(https://github.com/yuxng/YCB_Video_toolbox). For more information, please refer to their work.

**Comment by staceycy** [comment]
Thank you for your quick reply. @j96w 
I met another problem of missing defined functions 'quat2rotm'. 
I cannot find it in the repository.
Have you met this problem, and how do you solve it? 
Thank you very much : )

**Comment by j96w** [comment]
That's just a basic Matlab function. https://it.mathworks.com/help/robotics/ref/quat2rotm.html

**Comment by staceycy** [comment]
Thanks 👍 @j96w

**Comment by Ixion46** [comment]
The Folder results_3dCoordinate is no longer part of the YCB_Video_toolbox or I am blind and can not find it.
How to get it?
