### ISSUE TITLE
poor experimental results

### ISSUE THREAD

**Issue by huckl3b3rry87** [j96w/DenseFusion#140]
@j96w running on a Kinect2, where the images are downscaled from (1080,1920) to (480,640) as
```
img = img[300:780, 640:1280]
depth = depth[300:780, 640:1280])
```
and similar to [this issue](https://github.com/j96w/DenseFusion/issues/102), ``cam_scale`` was reduced to ``1000.0``, as the results were very poor, otherwise

After calibrating the camera, I am getting this result
![jumpy](https://user-images.githubusercontent.com/8204378/74370113-647e1980-4d8b-11ea-9b7f-577672bccbdc.gif)

or with a coordinate system 
![jumpy](https://user-images.githubusercontent.com/8204378/74372905-54b50400-4d90-11ea-84a7-baa35f1f06f3.gif)

Any ideas what might be going wrong?

If it helps some poses are
```
[-0.65687874 -0.29622098  1.00759838]
[ 0.35443226  0.52711563  0.60668457 -0.47797565]
[-0.64013799 -0.29069525  0.99237862]
[ 0.35168995  0.50609275  0.62459236 -0.47965476]
[-0.6409451  -0.29007845  0.9779653 ]
[ 0.36114991  0.51712236  0.61365279 -0.47495837]
[-0.63965378 -0.27483077  0.94999281]
[ 0.38290307  0.50501268  0.62593895 -0.45447536]
[-0.68891504 -0.25613858  0.96063731]
[ 0.36224944  0.51680428  0.6180552  -0.46871788]
[-0.74284063 -0.26807885  1.01151768]
[ 0.37367617  0.47725729  0.64413286 -0.46656666]
[-0.72971484 -0.27267355  1.02304178]
[ 0.36013067  0.48302501  0.66387707 -0.44301239]
[-0.7147548  -0.27369382  1.03266598]
[ 0.36364657  0.48264426  0.65677283 -0.4510711 ]
[-0.73962974 -0.31682062  1.04834394]
[ 0.31601388  0.48363191  0.64530514 -0.49981664]
[-0.73793128 -0.31206208  1.04883617]
[ 0.3186466   0.48528202  0.64587824 -0.49578927]
[-0.69890178 -0.2944833   1.02037061]
[ 0.35660433  0.50311739  0.63483259 -0.46550385]
[-0.74431053 -0.31800238  1.05657308]
[ 0.30737212  0.48656367  0.65604853 -0.4882402 ]
[-0.70962489 -0.29020834  1.03301129]
[ 0.36751163  0.49173057  0.65522027 -0.44025295]
[-0.74788274 -0.33912357  1.06476996]
[ 0.33436162  0.48290348  0.63500053 -0.50177772]
```

where, at least for the Z, it is pretty close, at about 100 cm, at times, but very jumpy

**Comment by huckl3b3rry87** [comment]
Given that I am using the Kinect, as given by [this article](https://shiffman.net/p5/kinect/), instead of  using ``cam_scale`` to calculate ``pt2``, I tried to scale my depth using this formula
```
depthInMeters = 1.0 / (rawDepth * -0.0030711016 + 3.3309495161);
```
however, results were degraded even worse

**Comment by huckl3b3rry87** [comment]
I also tried converting the depth image to a float
```
depth = self.cv_bridge.imgmsg_to_cv2(depth_msg, desired_encoding="16UC1")
depth = np.float32(depth)
```
as I am using [iai_kinect](https://github.com/code-iai/iai_kinect2/issues/388) to give me depth images

**Comment by huckl3b3rry87** [comment]
So, to debug I published the point cloud that I am sending to the NN and there are obvious errors 
![jump](https://user-images.githubusercontent.com/8204378/74398710-5f41be80-4dcd-11ea-98a6-85f547f06ce5.gif)

The points in white where I am moving the mouse over are the points that are sent to the NN.

Besides the fact that they are not located where they should be, I am wondering why there is a hole in the data where the mustard bottle is, that is why does it remove the depth points that are created by hitting the mustard bottle?

**Comment by huckl3b3rry87** [comment]
Ah, it looks like my comment 

> Besides the fact that they are not located where they should be, I am wondering why there is a hole in the data where the mustard bottle is, that is why does it remove the depth points that are created by hitting the mustard bottle?

Is addressed with this pic
![pic](https://user-images.githubusercontent.com/8204378/74466880-f39f3600-4e4c-11ea-9f3b-8a39fb1b8505.png)

**Comment by akeaveny** [comment]
Hi @huckl3b3rry87, @MyungHaSong,
Would you be willing to share your ROS wrapper? I'm currently implementing modifying @MrLuer's wrapper.

**Comment by avasalya** [comment]
@akeaveny  did you manage to implement ROS wrapper? could you please share?

and which segmentation method did you use as input to densefusion?

I have trained Densefusion on custom dataset based on linemod format, 

appreciate your help
thanks
