### ISSUE TITLE
Is the execution time invariant to number of objects where each object is of different class?

### ISSUE THREAD

**Issue by Abdul-Mukit** [j96w/DenseFusion#144]
Thank you for your amazing work!

My question is whether the execution time stays invariant to the number of objects in the image if the objects are of different classes.
e.g. let's say I have two images. The first one has 5 and the second one has 10 objects. Each object in both images is of a different class. Will the execution time increase linearly? If it changes, what is an estimate of the change?

Also, the same question if the objects are of the same class.

Thanks.

**Comment by j96w** [comment]
Hi, yes the time increase linearly. For each object, the model will process the color embedding with the CNN encoder-decoder and the geometry embedding with the MLPs. In your example, the second one with 10 objects will cost double the time of the first one. The class of the object won't affect the inference speed.

**Comment by Abdul-Mukit** [comment]
Thank you.
