### ISSUE TITLE
3D semantic point cloud

### ISSUE THREAD

**Issue by YJonmo** [j96w/DenseFusion#149]
Hi there,

Thanks for this excellent work.

I am a bit new in the field.
My question might be a bit irrelevant. But I would like to know how I can create the 3D semantic map (point cloud), when I have the camera pose + depth + semantic labels for every frame. 

Cheers,
Jacob

**Comment by j96w** [comment]
Hi, are you talking about works like SemanticFusion? Actually, we are focusing on different things.
