### ISSUE TITLE
Fail to run Evaluation on YCB_Video Dataset

### ISSUE THREAD

**Issue by hoangcuongbk80** [j96w/DenseFusion#15]
Hi,

I got the error when run `./experiments/scripts/eval_ycb.sh` as the following:

![1](https://user-images.githubusercontent.com/10355081/54284913-2687dc80-45a1-11e9-829f-89ea88487a2d.png)

Thanks!

**Comment by j96w** [comment]
You get this error because you have deleted this part of code:
https://github.com/j96w/DenseFusion/blob/813940ae2ae33fa0ccd65e778037e5882d3ad282/tools/eval_ycb.py#L234-L237
This exception happens when the object detector totally lost the target object in the scene, so no pixels from the segmentation of this object is found. When this happens, a vector with all zeros will be returned and be regarded as a failure case.

**Comment by MyungHaSong** [comment]
I got same error....

How can I solve this error??

**Comment by Taeuk-Jang** [comment]
I got the same error even I didn't modify any codes

**Comment by j96w** [comment]
Hi @Taeuk-Jang, could you show me more info about this error, for example, which line of code in eval_ycb.py cause it? I didn't have this problem myself.

**Comment by Taeuk-Jang** [comment]
Hi, @j96w, after downloading all the data, when I do 
`sh ./experiments/scripts/eval_ycb.sh`
it shows as it up as hoangcuongbk80 captured and it stops running

**Comment by Taeuk-Jang** [comment]
Oh is there no demo model that is trained?
would it be the reason?
Or is it possible to run a demo?

**Comment by MyungHaSong** [comment]
This error occurs when there is an empty matrix.

This problem can be solved by an exception of an empty matrix.

**Comment by ZJU-PLP** [comment]
Hi, when I run the matlab code "YCB_Video_toolbox/evaluate_poses_keyframe.m", I meet the problem! Who can help me ? Thanks a lot in advance!
`Error using load
Unable to read file 'Densefusion_iterative_result/0026.mat'. No such file or directory.

Error in evaluate_poses_keyframe (line 50)
    result_my = load(filename);`

**Comment by MaxChanger** [comment]
@j96w @hoangcuongbk80 I also meet this problem, in python3.6 pytorch1.0, and I find a solution in stackoverflow, but now i can't find the link, the reason maybe the version of numpy.

After I modify the version of numpy from 1.16 to 1.10.1, this mistake was resolved.

But I don't think it's the perfect solution to this problem, If you find the real reason for this problem, please let me know.

**Comment by hoangcuongbk80** [comment]
@MaxChanger 
I made it work, but do not remember how exactly I did it. You can try what I fixed from here:
https://github.com/hoangcuongbk80/Object-RPE/tree/master/DenseFusion

**Comment by MaxChanger** [comment]
@hoangcuongbk80  Thank you very much, I will try it later !
