### ISSUE TITLE
new testimages

### ISSUE THREAD

**Issue by Ixion46** [j96w/DenseFusion#154]
Hey Guys, thanks for your awesome Paper! 
I am not really good at programming. Can someone tell me how to test this paper on other videos or own images?
Best regards

**Comment by j96w** [comment]
Hi, you can modify the evaluation script to the new testing set. Basically, we need to load `img`,`depth`,`segmentation outputs` and `camera parameters` here:
https://github.com/j96w/DenseFusion/blob/f7af2d99a38890183fe1c97d84f6bf1488a175f5/tools/eval_ycb.py#L137-L140

**Comment by Ixion46** [comment]
Hey @j96w , sorry for my late answer. Just right now saw your response. This really helps me, but how can I get the segmentation outputs for my own images? I saw that there is a train.py and segnet.py in the folder vanillaSegmentation, do I need to train it on the same training-images before and then run the segnet on the testimages?
