### ISSUE TITLE
inference_linemod.py 

### ISSUE THREAD

**Issue by Lcomerun** [j96w/DenseFusion#156]
How can I get the "inference_linemod.py" code.

**Comment by j96w** [comment]
Hi, you can modify the `DenseFusion/tools/eval_linemod.py` for inference purposes. Basically, we just need to replace the for loop of the testdataloader to an RGB-D input stream. The `my_pred` is the final pose estimation result after refinement ('my_r': quaternion, 'my_t': translation).

**Comment by an99990** [comment]
@j96w but the model takes four arguments, you cant simply give the RGB and point cloud. Is it possible to provide more details
what is choose, idx ? how can we adapt this for real time purposes ?

`estimator(img, points, choose, idx)`

thank you
