### ISSUE TITLE
Visualiszation Code

### ISSUE THREAD

**Issue by SharadaJay** [j96w/DenseFusion#159]
Hi,

Could you please provide me the code for drawing the 3D Bounding boxes/ projecting the 3D points on the RGB images of the LineMOD dataset? I am having trouble figuring out how to visualize the results on images. 
Thanks.

**Comment by j96w** [comment]
Hi, please refer to [Issue#4](https://github.com/j96w/DenseFusion/issues/4), where we discussed how to visualize a 3d bbox on the image. An easier way might be directly projecting the object model pointcloud back to the image frame.
