### ISSUE TITLE
Why u use PSP Net to extract features?

### ISSUE THREAD

**Issue by MengHao666** [j96w/DenseFusion#164]
Thanks for that great work ,but I got confused about the usage of PSP Net.

In my undestanding, u use PSP Net to extract Height*Width*Drgb feature of cropped image.
But why not use resnet and just do some modifications? Is that PSPNet outperform the single resnet in practice?

Hope for any generous reply!

**Comment by j96w** [comment]
Hi, thanks for mention this question. The pspnet we are using is based on resnet. You can find how we create the resnet as encoder in `lib/extractors.py`. The decoder is simply several up-sampling layers, which could be found in `lib/pspnet.py`. Please regard this network as a simplified version of the original pspnet, which contains some modifications based on the resnet. Feel free to change this network to other encoder-decoder networks you prefer.

**Comment by MengHao666** [comment]
Thanks for suggestions，i will try other networks to see any improvement or not.
