### ISSUE TITLE
Evaluation on Linemod_preprocessed

### ISSUE THREAD

**Issue by KatharinaSchmidt** [j96w/DenseFusion#166]
Hello, 
I am able to train with your awesome work. 
I trained on Linemod_preprocessed, now I want to evaluate on the same dataset. 
Do I also have to run vanilla SegNet on Linemod? If I use `python train.py --dataset_root=../datasets/linemod/Linemod_preprocessed` I get an error message, saying: 
```
FileNotFoundError: [Errno 2] No such file or directory: '../datasets/linemod/Linemod_preprocessed/data_syn/030571-label.png'
```
Do I need to change a path or is vanilla SegNet only for ycb?

Furthermore I also got some issues evaluating linemod with`./experiments/scripts/eval_linemod.sh`. After loading the object buffers I get this: 
```
File "/home/katharina/Schreibtisch/DenseFusion-Pytorch-1.0/datasets/linemod/dataset.py", line 218, in mask_to_bbox
    _, contours, _ = cv2.findContours(mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by jpizarrom** [comment]
solution in https://github.com/j96w/DenseFusion/issues/127#issuecomment-559854709

**Comment by KatharinaSchmidt** [comment]
Evaluation works now, thank you. 
But I still got the issue with vanilla SegNet as described above.

**Comment by eneSadi** [comment]
How did you solve the problem with the SegNet? -->
"Do I need to change a path or is vanilla SegNet only for ycb?"
