### ISSUE TITLE
Training does not start

### ISSUE THREAD

**Issue by Ixion46** [j96w/DenseFusion#175]
Hey @j96w and ofcourse all the others! I could need help with a problem. I created some own dataset with NDDS and hopefully configured it in the same way the ycb-dataset was configured. Now I tried to train on some small example pictures, but the training never starts. Does somebody have an idea why?
Here is the error that comes up if I interrupt the process with the keyboard
<img width="733" alt="error" src="https://user-images.githubusercontent.com/60901212/91518905-85eebf00-e8f1-11ea-825d-ad9ecd59558f.png">

**Comment by Ixion46** [comment]
I think I came a little closer to the solution. The problem is that the execution of the code keep stuck in the following lines in datasets/ycb/dataset.py .

```

        while 1:
            idx = np.random.randint(0, len(obj))
            mask_depth = ma.getmaskarray(ma.masked_not_equal(depth, 0))
            mask_label = ma.getmaskarray(ma.masked_equal(label, obj[idx]))
            mask = mask_label * mask_depth
            if len(mask.nonzero()[0]) > self.minimum_num_pt:
                break
```

The mask_depth and mask_label matrices are full with False values

**Comment by KatharinaSchmidt** [comment]
Make sure that your mask has the same colors as in linemod-datatset. 
The background has to be white and the object has to be white. You also have to check that your mask is an array like [X,Y,3]. For white color all three channel muste be 255 and for black color all three channel have to be 0.

**Comment by Ixion46** [comment]
Thanks for your advice, but I try to implement the training via the "ycb part". There you only got color-pictures , depth and label pictures, but I think that my label pictures are wrong , when I see your answer. Because In the data_syn part of ycb, the labels have black background and grey objects.

**Comment by WinglokWong616** [comment]
> Thanks for your advice, but I try to implement the training via the "ycb part". There you only got color-pictures , depth and label pictures, but I think that my label pictures are wrong , when I see your answer. Because In the data_syn part of ycb, the labels have black background and grey objects.

Would you be so kind to share more details of your final solution? I encountered the exact situation when training my own datasets(created by Labelfusion, configured by the order of YCB datasets) via "ycb part". Looking forward to your reply, it will be of much help to our team.
