### ISSUE TITLE
The download script doesn't work.

### ISSUE THREAD

**Issue by bgyooPtr** [j96w/DenseFusion#176]
I get a 404 error as shown below.
DNS server is using 1.1.1.1 and 1.0.0.1.
Is there any other way to get that dataset?

> Downloading the YCB-Video Dataset
> Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
> ERROR: could not open HSTS store at '/home/bgyoo/.wget-hsts'. HSTS will be disabled.
> --2020-09-11 12:58:50--  https://docs.google.com/uc?export=download&confirm=&id=1if4VoEXNx9W3XCn0Y7Fp15B4GpcYbyYi
> Resolving docs.google.com (docs.google.com)... 172.217.175.14, 2404:6800:4004:81c::200e
> Connecting to docs.google.com (docs.google.com)|172.217.175.14|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: unspecified [text/html]
> Saving to: ‘YCB_Video_Dataset.zip’
> 
> YCB_Video_Dataset.zip             [ <=>                                              ]   3.04K  --.-KB/s    in 0s
> 
> 2020-09-11 12:58:50 (9.46 MB/s) - ‘YCB_Video_Dataset.zip’ saved [3110]
> 
> Archive:  YCB_Video_Dataset.zip
>   End-of-central-directory signature not found.  Either this file is not
>   a zipfile, or it constitutes one disk of a multi-part archive.  In the
>   latter case the central directory and zipfile comment will be found on
>   the last disk(s) of this archive.
> unzip:  cannot find zipfile directory in one of YCB_Video_Dataset.zip or
>         YCB_Video_Dataset.zip.zip, and cannot find YCB_Video_Dataset.zip.ZIP, period.
> Downloading the trained checkpoints...
> Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
> ERROR: could not open HSTS store at '/home/bgyoo/.wget-hsts'. HSTS will be disabled.
> --2020-09-11 12:58:51--  https://docs.google.com/uc?export=download&confirm=&id=1bQ9H-fyZplQoNt1qRwdIUX5_3_1pj6US
> Resolving docs.google.com (docs.google.com)... 172.217.175.14, 2404:6800:4004:81c::200e
> Connecting to docs.google.com (docs.google.com)|172.217.175.14|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2020-09-11 12:58:51 ERROR 404: Not Found.
> 
> done

**Comment by qsh-zh** [comment]
I encounter the same issue. YCB_Video_Dataset and checkpoints are unavailable.

**Comment by weihaosky** [comment]
same problem

**Comment by qsh-zh** [comment]
I guess it is the issue caused by the updated google drive viruses check mechanism. [This link](https://drive.google.com/drive/folders/19ivHpaKm9dOrr12fzC8IDFczWRPFxho7) still work. An alternative to download in the terminal can be
```shell
curl -c /tmp/cookies "https://drive.google.com/uc?export=download&id=1YFUra533pxS_IHsb9tB87lLoxbcHYXt8" > /tmp/delete_me.html
curl -L -b /tmp/cookies "https://drive.google.com$(cat /tmp/delete_me.html | grep -Po 'uc-download-link" [^>]* href="\K[^"]*' | sed 's/\&amp;/\&/g')" > Linemod_preprocessed.zip
```
This works on my machine.
