### ISSUE TITLE
Can the model you give meet the accuracy of the paper?

### ISSUE THREAD

**Issue by lzrrr33** [j96w/DenseFusion#178]
when i try to eval the model you give with  _evaluate_poses_keyframe.m_ ,i get a poor reult **0.6763085650852565** with add < 2cm .Is my evaluation method wrong? thanks for your reply !

**Comment by LennardBo** [comment]
What exactly do you mean with this number? The overall proportion of ADD<2cm? 
However, I was actually wondering the same thing. Following the same procedure as described in the repository, I get the unrefined results  at the bottom in Matlab. I changed only two things: Catching the issue described in #91 and printing out the values as seen below in Matlab.

Here i = 3 is referring to the index corresponding to the unrefined results as in `evaluate_poses_keyframe.m`:
class 1, i 3: AUC(s):95.31, ADD-s<2cm:100.00, AUC:70.74, ADD<2cm:70.68
class 2, i 3: AUC(s):92.44, ADD-s<2cm:98.96, AUC:86.87, ADD<2cm:88.71
class 3, i 3: AUC(s):95.05, ADD-s<2cm:100.00, AUC:90.74, ADD<2cm:96.28
class 4, i 3: AUC(s):93.74, ADD-s<2cm:96.94, AUC:84.65, ADD<2cm:82.50
class 5, i 3: AUC(s):95.81, ADD-s<2cm:100.00, AUC:90.96, ADD<2cm:94.12
class 6, i 3: AUC(s):95.73, ADD-s<2cm:100.00, AUC:79.61, ADD<2cm:58.97
class 7, i 3: AUC(s):94.38, ADD-s<2cm:99.53, AUC:89.41, ADD<2cm:93.93
class 8, i 3: AUC(s):97.20, ADD-s<2cm:100.00, AUC:95.80, ADD<2cm:100.00
class 9, i 3: AUC(s):89.30, ADD-s<2cm:92.95, AUC:79.57, ADD<2cm:76.37
class 10, i 3: AUC(s):90.12, ADD-s<2cm:89.45, AUC:76.87, ADD<2cm:59.10
class 11, i 3: AUC(s):93.61, ADD-s<2cm:100.00, AUC:86.89, ADD<2cm:86.84
class 12, i 3: AUC(s):94.40, ADD-s<2cm:99.61, AUC:87.50, ADD<2cm:86.20
class 13, i 3: AUC(s):86.10, ADD-s<2cm:60.59, AUC:5.07, ADD<2cm:0.00
class 14, i 3: AUC(s):95.25, ADD-s<2cm:100.00, AUC:83.81, ADD<2cm:79.72
class 15, i 3: AUC(s):92.14, ADD-s<2cm:95.46, AUC:83.85, ADD<2cm:82.59
class 16, i 3: AUC(s):89.50, ADD-s<2cm:98.35, AUC:32.25, ADD<2cm:0.00
class 17, i 3: AUC(s):90.21, ADD-s<2cm:98.90, AUC:77.27, ADD<2cm:49.72
class 18, i 3: AUC(s):95.08, ADD-s<2cm:100.00, AUC:89.10, ADD<2cm:91.05
class 19, i 3: AUC(s):71.52, ADD-s<2cm:77.67, AUC:24.87, ADD<2cm:0.00
class 20, i 3: AUC(s):70.17, ADD-s<2cm:72.29, AUC:25.17, ADD<2cm:11.14
class 21, i 3: AUC(s):92.21, ADD-s<2cm:100.00, AUC:50.81, ADD<2cm:0.00
class 22, i 3: AUC(s):91.19, ADD-s<2cm:94.91, AUC:74.19, ADD<2cm:68.18

**Comment by lzrrr33** [comment]
@LennardBo thanks for your reply，I have solved this problem！
