### ISSUE TITLE
symmetry objects

### ISSUE THREAD

**Issue by Ixion46** [j96w/DenseFusion#180]
Hey @j96w , thanks for your great work. I finaly get really good results.
I still have one question left : What kind of symmetry is meant in the dataset.py file in ycb?
`        self.symmetry_obj_idx = [12, 15, 18, 19, 20]`

I dont get why the bleach cleanser is a symmetrical object and the sugar-box or a can not? I hope you can help me with that.
Best Regards Ixion

**Comment by j96w** [comment]
Hi, so to be honest, the definition of symmetry objects are from prior works like PoseCNN. I'm not sure about the exact definition but I think they have taken the texture and color into consideration. For some objects like the sugar-box, you can tell which surface (front or back) is visible in the camera image by its testure.
