### ISSUE TITLE
Data visualisation 

### ISSUE THREAD

**Issue by hamza-04** [j96w/DenseFusion#19]
Hi @j96w  , thank's for your work , i'm really stack on visualization part for days , could you just explain to me ( if it possible with enough details pls ) how to show , detected objects of linemod data on the videos files ( or data photos ) in real time , 

I trained data and also make an evaluation , and result was as expected , but i wan't this part of visualization  in real time how to this see object mesh on videos , and also how to work with a camera in real time , 

Thank you  in advance .
Hamza

**Comment by j96w** [comment]
Hi @hamza-04 ,  I think @iris0329 and I have introduced the detail about how to visualize a 3d bbox on the image in [Issue#4](https://github.com/j96w/DenseFusion/issues/4). Another easier way might be directly projecting the object model pointcloud (named `points.xyz` in `YCB-Video-Dataset/models/XXX`) back to the image frame.

**Comment by hamza-04** [comment]
thank you for your answer  @j96w , i'm going to try more following you suggestions !
