### ISSUE TITLE
torch.utils.ffi is deprecated. Please use cpp extensions instead

### ISSUE THREAD

**Issue by GalenOOO** [j96w/DenseFusion#20]
I'm using pytorch 1.0.1 instead of 0.4.1. When I ran ./experiments/scripts/train_linemod.sh, then "ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead" appears.Any solutions except changing the pytorch's version?

**Comment by j96w** [comment]
This problem comes from the KNN library, which is the only problem currently to run this repo with Pytorch 1.0. We will first label this as an enhancement.

**Comment by huipengly** [comment]
@j96w  I have changed code to support PyTorch 1.0. I use a knn lib from here. [torchKNN](https://github.com/foolyc/torchKNN)

I want to pull request to your repository, but it only have a master branch. Could you please create a branch for PyTorch 1.0?

This is my code. I test it in Pytorch 1.0.1 with cuda10.

https://github.com/huipengly/DenseFusion/tree/pytorch-1.0

**Comment by j96w** [comment]
@huipengly Sounds great. Thanks! I have created a branch named `Pytorch-1.0` for you to pull request.

**Comment by j96w** [comment]
@GalenOOO Could you try on this branch to see whether your problem solved?

**Comment by GalenOOO** [comment]
@huipengly when I run the code in branch Pytorch-1.0, ImportError: cannot import name 'knn_pytorch' occured.What's the matter?

**Comment by huipengly** [comment]
Maybe there is a bug in `DenseFusion/lib/knn/__init__.py` line 7.

go to `DenseFusion/lib/knn`, try this python code.
```python
import torch
from knn_pytorch import knn_pytorch
```

If you can import knn_pytorch, the lib is ok. 

Try to change the import code in \_\_init\_\_.py line 7. I don't know how to fix this bug.

**Comment by GalenOOO** [comment]
@huipengly Maybe replacing the original line7 with "from knn_pytorch import knn_pytorch" works.I just tried training and evaling with no errors.
Many thanks!

**Comment by gaobaoding** [comment]
> @huipengly Maybe replacing the original line7 with "from knn_pytorch import knn_pytorch" works.I just tried training and evaling with no errors.
> Many thanks!

It doesn't work for me with pycharm, do you think it's problem with IDE configuration?

**Comment by gaobaoding** [comment]
> Maybe there is a bug in `DenseFusion/lib/knn/__init__.py` line 7.
> 
> go to `DenseFusion/lib/knn`, try this python code.
> 
> ```python
> import torch
> from knn_pytorch import knn_pytorch
> ```
> 
> If you can import knn_pytorch, the lib is ok.
> 
> Try to change the import code in __init__.py line 7. I don't know how to fix this bug.

I tried in python code, the lib is fine, but I still got this bug in pycharm. have you fixed it?

**Comment by huipengly** [comment]
> > @huipengly Maybe replacing the original line7 with "from knn_pytorch import knn_pytorch" works.I just tried training and evaling with no errors.
> > Many thanks!
> 
> It doesn't work for me with pycharm, do you think it's problem with IDE configuration?

I use it with pycharm. Can you show me the error log?

**Comment by gaobaoding** [comment]
> > > @huipengly Maybe replacing the original line7 with "from knn_pytorch import knn_pytorch" works.I just tried training and evaling with no errors.
> > > Many thanks!
> > 
> > 
> > It doesn't work for me with pycharm, do you think it's problem with IDE configuration?
> 
> I use it with pycharm. Can you show me the error log?

It's ok now. The Inspection info doesn't affect during running. Thanks!
