### ISSUE TITLE
some confusion about loss calculation

### ISSUE THREAD

**Issue by ahaheng** [j96w/DenseFusion#22]
Thank you for sharing your codes.
I have some confusion about the dis_calculation in the stage of pose estimation.
`pred = torch.add(torch.bmm(model_points, base), points + pred_t)`
why not：
`pred = torch.add(torch.bmm(model_points, base),  pred_t)`
Thank you and looking forward to your reply.

**Comment by j96w** [comment]
Please refer to [Issue#7](https://github.com/j96w/DenseFusion/issues/7).
