### ISSUE TITLE
Why adding "points" in loss.py? 

### ISSUE THREAD

**Issue by syb7573330** [j96w/DenseFusion#23]
Thanks for sharing the code, amazing work! 

I am reading your code, but I found that in loss.py file line 38, when you calculate the loss, why you also add **points**? see the copied code below:  

`pred= torch.add(torch.bmm(model_points, base), points + pred_t)`

**Comment by j96w** [comment]
Please refer to [Issue#7](https://github.com/j96w/DenseFusion/issues/7).
