### ISSUE TITLE
Inconsistence between equation (2) in the paper and code implementation

### ISSUE THREAD

**Issue by syb7573330** [j96w/DenseFusion#24]
Equation (2) in the paper detects the closest point from **predicted** model points to each of **ground truth** model points for symmetric shapes which is consistent with the equation (6) in PoseCNN paper, but in the code implementation (line 44-47 in lib/loss.py) you instead find the closest point from **ground truth** model to each **predicted** model point, which is opposite. Can you explain? Because those two metrics are different. Thanks!

**Comment by j96w** [comment]
There isn't too much difference when the model points are from the same one. You can switch them during training, there is no strict rule.
