### ISSUE TITLE
Potential bug in lib.loss.loss_calculation

### ISSUE THREAD

**Issue by SergioRAgostinho** [j96w/DenseFusion#3]
Disclaimer: I haven't read the paper

That being said, this looks very suspicious.
https://github.com/j96w/DenseFusion/blob/42a21e76ff5391d3703d4e144a0831faf6fbdf43/lib/loss.py#L38

It should be only
```python
pred = torch.add(torch.bmm(model_points, base), pred_t)
```

like you have in `loss_refiner.py`. I don't see a reason to add the `points` you acquired from the camera here. Especially because you compute the point to point distance error a couple of lines below
https://github.com/j96w/DenseFusion/blob/42a21e76ff5391d3703d4e144a0831faf6fbdf43/lib/loss.py#L49

**Comment by SergioRAgostinho** [comment]
You're outputting a per point difference in the translation component.

**Comment by j96w** [comment]
> You're outputting a per point difference in the translation component.

Yes. So it's a per point offset translation estimation.

**Comment by flowtcw** [comment]
> Disclaimer: I haven't read the paper
> 
> That being said, this looks very suspicious.
> 
> https://github.com/j96w/DenseFusion/blob/42a21e76ff5391d3703d4e144a0831faf6fbdf43/lib/loss.py#L38
> 
> It should be only
> 
> ```python
> pred = torch.add(torch.bmm(model_points, base), pred_t)
> ```
> 
> like you have in `loss_refiner.py`. I don't see a reason to add the `points` you acquired from the camera here. Especially because you compute the point to point distance error a couple of lines below
> 
> https://github.com/j96w/DenseFusion/blob/42a21e76ff5391d3703d4e144a0831faf6fbdf43/lib/loss.py#L49

hi,do you solve this problem that 
`pred = torch.add(torch.bmm(model_points, base), points + pred_t) `
why add points

**Comment by j96w** [comment]
Hi @flowtcw,
Since DenseFusion is a per-point level translation estimation, the network is predicting the offset translation, which is based on the location of each input point. The refiner is a global level translation estimation in order to achieve fast iterative inference speed. More info: [Issue#7](https://github.com/j96w/DenseFusion/issues/7).
