### ISSUE TITLE
Evaluation on LineMOD

### ISSUE THREAD

**Issue by j96w** [j96w/DenseFusion#30]
Thank you for your help. Sorry to bother you again. I still have some questions. 
1.The max default number of epochs to train is 500. When training 104 epochs on ycb, the _dis_ is 0.0090381440936. But it costs long time. And the ycb 
 trained_models you provide is `pose_refine_model_69_0.009449292959118935.pth`. So how to determine the epoch of training for pose refine model? The lower the dis, the better the model? How to prevent overfitting?

2.When evaluation on LineMOD Dataset, the final content of eval_result_logs.txt is as follows:

No.13390 NOT Pass! Distance: 0.0217275395989
No.13391 Pass! Distance: 0.0048154219985
No.13392 Pass! Distance: 0.0142814125866
No.13393 Pass! Distance: 0.00356977432966
No.13394 Pass! Distance: 0.00472941761836
No.13395 Pass! Distance: 0.00784354563802
No.13396 Pass! Distance: 0.0127922594547
No.13397 Pass! Distance: 0.00581285078079
No.13398 NOT Pass! Distance: 0.0267377775162
No.13399 Pass! Distance: 0.00628646928817
No.13400 Pass! Distance: 0.0146940667182
No.13401 NOT Pass! Distance: 0.0340396799147
No.13402 NOT Pass! Distance: 0.0713591426611
No.13403 NOT Pass! Distance: 0.0522820688784
No.13404 Pass! Distance: 0.0038491380401
No.13405 NOT Pass! Distance: 0.0213586390018
No.13406 Pass! Distance: 0.00927203428
Object 1 success rate: 0
Object 2 success rate: 0
Object 4 success rate: 0
Object 5 success rate: 0
Object 6 success rate: 0
Object 8 success rate: 0
Object 9 success rate: 0
Object 10 success rate: 0
Object 11 success rate: 1
Object 12 success rate: 0
Object 13 success rate: 0
Object 14 success rate: 0
Object 15 success rate: 0
ALL success rate: 0

Is anything wrong with evaluation on LineMOD Dataset？How can I get an evaluation result similar to YCB_Video Dataset run with MATLAB?

 Thank you in advance.

_Originally posted by @sunshantong in https://github.com/j96w/DenseFusion/issues/7#issuecomment-482135726_

**Comment by j96w** [comment]
Hi @sunshantong, I re-open your questions here. Hope you can find your answers.

Reply to Q2:
Could you double check whether your `tools/eval_linemod.py` is the one I provided? Since I have just re-run the `tools/eval_linemod.py` with the released checkpoints for LineMOD: `pose_model_9_0.01310166542980859.pth` & `pose_refine_model_493_0.006761023565178073.pth`, the result is correct. Here the result I get in the `experiments/eval_result/linemod/eval_result_logs.txt`:

No.13395 Pass! Distance: 0.009271996931017516
No.13396 Pass! Distance: 0.01369065264175427
No.13397 Pass! Distance: 0.006658221124601324
No.13398 Pass! Distance: 0.006385782737424083
No.13399 Pass! Distance: 0.006775527773388155
No.13400 Pass! Distance: 0.014295331124580606
No.13401 NOT Pass! Distance: 0.03540023064848053
No.13402 NOT Pass! Distance: 0.07267292932944466
No.13403 NOT Pass! Distance: 0.055387656278400726
No.13404 Pass! Distance: 0.003850689928203615
No.13405 NOT Pass! Distance: 0.021674528191168697
No.13406 Pass! Distance: 0.01262910184313126
Object 1 success rate: 0.9275500476644424
Object 2 success rate: 0.933074684772066
Object 4 success rate: 0.9470588235294117
Object 5 success rate: 0.937007874015748
Object 6 success rate: 0.9610778443113772
Object 8 success rate: 0.8721506442021804
Object 9 success rate: 0.9211267605633803
Object 10 success rate: 0.9981185324553151
Object 11 success rate: 1.0
Object 12 success rate: 0.9238820171265462
Object 13 success rate: 0.9724208375893769
Object 14 success rate: 0.9577735124760077
Object 15 success rate: 0.9298751200768491
ALL success rate: 0.9447179946284691

If you are evaluating your trained checkpoints, just modify the `experiments/scripts/eval_linemod.sh` and replace the model name with the one you want to test.

Reply to Q1:
Yes, you are right. The `dis` here refers to the ADD distance between the model_points transformed by the prediction and the ground truth. So it is the lower the better. About how to prevent over-fitting, we have introduced the techniques we applied to prevent overfitting in `README`, where we introduced 3 small data-augmentation methods based on the standard dataset. About how to determine the epoch of switching between the training of the DenseFusion model and the Refinement one, the switch only appears when the DenseFusion model is over-fitting. You can either adjust this margin or use the one we provided in this repo (See `README` for more information).

**Comment by sunshantong** [comment]
Thank you for your reply. I just re-downloaded the latest code in this repo  and evaluated it on lineMOD again. I also re-downloaded the trained_checkpoints (`pose_model_9_0.01310166542980859.pth & pose_refine_model_493_0.006761023565178073.pth`) on Google drive. But the results in the `experiments/eval_result/linemod/eval_result_logs.txt` are still problematic:

No.13401 NOT Pass! Distance: 0.0355636792823
No.13402 NOT Pass! Distance: 0.0701816126631
No.13403 NOT Pass! Distance: 0.0532170703425
No.13404 Pass! Distance: 0.0045910989795
No.13405 NOT Pass! Distance: 0.0262542191895
No.13406 Pass! Distance: 0.0116018552459
Object 1 success rate: 0
Object 2 success rate: 0
Object 4 success rate: 0
Object 5 success rate: 0
Object 6 success rate: 0
Object 8 success rate: 0
Object 9 success rate: 0
Object 10 success rate: 0
Object 11 success rate: 0
Object 12 success rate: 0
Object 13 success rate: 0
Object 14 success rate: 0
Object 15 success rate: 0
ALL success rate: 0

And the evaluation on YCB-video is correct. I do not know what's wrong with LineMOD. Looking forward to your suggestions.

Thanks in advance,

**Comment by j96w** [comment]
Hi, this is becoming super weird. So from your listed `eval_result_logs.txt `, we can see there are testing results that are evaluated as `PASS!`, which means there should be at least one success rate larger than 0. Could you double check whether the `success_count[i]`, `num_count[i]` have been turned into float before doing the `success_count[i] / num_count[i] `?

**Comment by sunshantong** [comment]
Yeah, it is. Thank you so much!
