### ISSUE TITLE
module 'lib.knn.knn_pytorch' has no attribute 'knn'

### ISSUE THREAD

**Issue by qingnanli** [j96w/DenseFusion#33]
Hi, thanks for sharing your code!
I downloaded the latest version of DenseFusion-Pytorch-1.0. When I ran ./experiments/scripts/train_ycb.sh, I got an error 'AttributeError: module 'lib.knn.knn_pytorch' has no attribute 'knn'' . My python version is 3.6.8 |Anaconda custom (64-bit) and the pytorch version is 1.0.1.post2. 

I tried to insert pdb.set_trace() in the line 20 of ./lib/knn/\_init\_.py 

    inds = torch.empty(query.shape[0], self.k, query.shape[2]).long().cuda()

    #import pdb
    #pdb.set_trace()
    knn_pytorch.knn(ref, query, inds)

    return inds

I print dir(knn_pytorch) which shows the following messages:

    (Pdb) p dir(knn_pytorch)
    ['__doc__', '__loader__', '__name__', '__package__', '__path__', '__spec__']

It seems that the module knn_pytorch doesn't have the knn. How can I solve this error? Please help me. 

The details are as follows:

    + set -e
    + export PYTHONUNBUFFERED=True
    + PYTHONUNBUFFERED=True
    + export CUDA_VISIBLE_DEVICES=0
    + CUDA_VISIBLE_DEVICES=0
    + python3 ./tools/train.py --dataset ycb --dataset_root ./datasets/ycb/YCB_Video_Dataset
    /home/qingqing/Downloads/qingqing_disk/p4600_disk/DenseFusion/lib/transformations.py:1912:      UserWarning: failed to import module _transformations
     warnings.warn('failed to import module %s' % name)
    96189
    2949
    >>>>>>>>----------Dataset loaded!---------<<<<<<<<
    length of the training set: 96189
    length of the testing set: 2949
    number of sample points on mesh: 500
    symmetry object list: [12, 15, 18, 19, 20]
    /home/qingqing/anaconda3/lib/python3.6/site-packages/torch/nn/_reduction.py:49: UserWarning:    size_average and reduce args will be deprecated, please use reduction='mean' instead.
     warnings.warn(warning.format(ret))
    2019-04-23 10:20:35,077 : Train time 00h 00m 00s, Training started
    /home/qingqing/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py:2351:   UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
     warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
    /home/qingqing/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py:2423:    UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False    since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
      "See the documentation of nn.Upsample for details.".format(mode))
    /home/qingqing/anaconda3/lib/python3.6/site-packages/torch/nn/modules/upsampling.py:129:     UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
      warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
    /home/qingqing/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py:92:     UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to   include dim=X as an argument.
      input = module(input)
    2019-04-23 10:20:36,413 : Train time 00h 00m 01s Epoch 1 Batch 1 Frame 8     Avg_dis:0.1779076661914587
    Traceback (most recent call last):
      File "./tools/train.py", line 237, in <module>
        main()
      File "./tools/train.py", line 140, in main
        loss, dis, new_points, new_target = criterion(pred_r, pred_t, pred_c, target, model_points, idx,     points, opt.w, opt.refine_start)
      File "/home/qingqing/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line     489, in __call__
        result = self.forward(*input, **kwargs)
      File "/home/qingqing/Downloads/qingqing_disk/p4600_disk/DenseFusion/lib/loss.py", line 83, in forward
        return loss_calculation(pred_r, pred_t, pred_c, target, model_points, idx, points, w, refine, self.num_pt_mesh, self.sym_list)
      File "/home/qingqing/Downloads/qingqing_disk/p4600_disk/DenseFusion/lib/loss.py", line 44, in loss_calculation
        inds = knn(target.unsqueeze(0), pred.unsqueeze(0))
      File "/home/qingqing/Downloads/qingqing_disk/p4600_disk/DenseFusion/lib/knn/__init__.py", line 23, in forward
        knn_pytorch.knn(ref, query, inds)
    AttributeError: module 'lib.knn.knn_pytorch' has no attribute 'knn'

**Comment by Mars-y470** [comment]
Hi, did you slove it? I was embracing with the same error , it's quite trouble.

**Comment by Mars-y470** [comment]
@qingnanli try to recomplile DenseFusion/lib/knn, it seems to work for me .Good luck

**Comment by qingnanli** [comment]
> @qingnanli try to recomplile DenseFusion/lib/knn, it seems to work for me .Good luck

@Mars-y470 Thanks for your timely help! It worked!

**Comment by HuaWeitong** [comment]
@Mars-y470 May I ask how to recompile it? I tried both ‘python setup.py build’ and 'python setup.py install' but it didn't work.Thanks.

**Comment by whuwuh** [comment]
@qingnanli May I ask how to recompile it? I tried 'python setup.py build' and 'python setup.py install' but it still doesn't work. Thanks

**Comment by whuwuh** [comment]
@HuaWeitong I met the same problem as you, have you solved it?

**Comment by HuaWeitong** [comment]
> @HuaWeitong I met the same problem as you, have you solved it?

Not yet...

**Comment by qingnanli** [comment]
@HuaWeitong @whuwuh you can unzip the *.egg file and move the *so and knn_pytorch.py into the knn root folder. It works for me. But during the YCB training procedure, I got another error #41 'RuntimeError: the derivative for 'index' is not implemented'. This problem has been bothering me for a long time.

**Comment by HuaWeitong** [comment]
> @HuaWeitong @whuwuh you can unzip the *.egg file and move the *so and knn_pytorch.py into the knn root folder. It works for me. But during the YCB training procedure, I got another error #41 'RuntimeError: the derivative for 'index' is not implemented'. This problem has been bothering me for a long time.

It works now, thanks very much!

**Comment by whuwuh** [comment]
@qingnanli thank you very much for your answer, I just modified one line code in the __init__.py file from 'from lib.knn.knn_pytorch' to 'from lib.knn.knn_pytorch.knn_pytorch', and I works now.

**Comment by davidemariafabris** [comment]
@qingnanli Thank you guys for your precious help, I was wandering where the *.egg file is in the repository, cause I cannot find it. Could  you help me? Can you confirm me that as soon as I unzip it I get the *so and knn_pytorch.py? Thank you.

**Comment by Fiona730** [comment]
@qingnanli I have met the same problem, but I can only find .so file, and there is no .egg file in my lib/knn. Is any additional instruction needed to generate this .egg file? Thank you for your help.

**Comment by NodYoung** [comment]
@Fiona730 I met the same problem as you, have you solved it?

**Comment by liyi14** [comment]
changing [L7 in __init__.py](https://github.com/j96w/DenseFusion/blob/master/lib/knn/__init__.py#L7)  to `from lib.knn.knn_pytorch import knn_pytorch` works for me

**Comment by hygxy** [comment]
@liyi14 Hi, i tried your solution and get the following eror:
ImportError: cannot import name 'knn_pytorch' from 'lib.knn.knn_pytorch' (unknown location)

how can i solve this error? thanks in advance

**Comment by BacheryChan** [comment]
@qingnanli @HuaWeitong @Fiona730 I met the same problem but cannot find any *.egg file, where can I get them? Thanks

@whuwuh @liyi14 I also tried your way but got the same error as @hygxy, how can I solve it? Thank you

**Comment by BacheryChan** [comment]
@Fiona730 run `python setup build` and `python setup install` and you will get the .egg file in `dist/` folder and the .so file in `build/lib.*` folder

**Comment by yanzhou-li** [comment]
you can do "from lib.knn.knn_pytorch import knn_pytorch" in init.py. it works for me

**Comment by 704051419** [comment]
@BacheryChan  where is setup.py? didn't see that

**Comment by cm107** [comment]
@704051419  It's under ```lib/knn```

**Comment by SKKSaikia** [comment]
@BacheryChan  Thanks! works for me. I ran it in Singularity container for 1.0 branch.

**Comment by karlita101** [comment]
I was wondering if anyone had this issue when running train.py [MaskedFusion
](https://github.com/kroglice/MaskedFusion) which was largely based on this code.
 
My errors ( as is):
" cannot import name 'knn_pytorch' from 'lib.knn.knn_pytorch' (unknown location)"
 
Not quite sure what else it can be at this point, the _from lib.knn.knn_pytorch import knn_pytorch_ has already been taken care of.

Any help would be much appreciated. See full message when running the _experiments/scripts/train_linemod.sh_ below

----------------------------------------------------------------------------------------------------------------------------------------

`+ set -e
+ export PYTHONUNBUFFERED=True
+ export PYTHONWARNINGS=ignore
+ export CUDA_VISIBLE_DEVICES=0
+ date +%s
+ start=1614646436
+ python3 ./tools/train.py --nepoch 101 --dataset linemod --dataset_root ./datasets/linemod/Linemod_preprocessed
Traceback (most recent call last):
  File "./tools/train.py", line 20, in <module>
    from lib.loss import Loss
  File "/content/MaskedFusion/lib/loss.py", line 9, in <module>
    from lib.knn.__init__ import KNearestNeighbor
  File "/content/MaskedFusion/lib/knn/__init__.py", line 8, in <module>
    from lib.knn.knn_pytorch import knn_pytorch
ImportError: cannot import name 'knn_pytorch' from 'lib.knn.knn_pytorch' (unknown location)`

**Comment by dapaopaopao** [comment]
> I was wondering if anyone had this issue when running train.py [MaskedFusion ](https://github.com/kroglice/MaskedFusion) which was largely based on this code.
> 
> My errors ( as is):
> " cannot import name 'knn_pytorch' from 'lib.knn.knn_pytorch' (unknown location)"
> 
> Not quite sure what else it can be at this point, the _from lib.knn.knn_pytorch import knn_pytorch_ has already been taken care of.
> 
> Any help would be much appreciated. See full message when running the _experiments/scripts/train_linemod.sh_ below
> 
> `+ set -e
> 
> * export PYTHONUNBUFFERED=True
> * export PYTHONWARNINGS=ignore
> * export CUDA_VISIBLE_DEVICES=0
> * date +%s
> * start=1614646436
> * python3 ./tools/train.py --nepoch 101 --dataset linemod --dataset_root ./datasets/linemod/Linemod_preprocessed
>   Traceback (most recent call last):
>   File "./tools/train.py", line 20, in 
>   from lib.loss import Loss
>   File "/content/MaskedFusion/lib/loss.py", line 9, in 
>   from lib.knn.**init** import KNearestNeighbor
>   File "/content/MaskedFusion/lib/knn/**init**.py", line 8, in 
>   from lib.knn.knn_pytorch import knn_pytorch
>   ImportError: cannot import name 'knn_pytorch' from 'lib.knn.knn_pytorch' (unknown location)`

 @karlita101    I met the same problem as you, have you solved it?

**Comment by barvin04** [comment]
> @Fiona730 run `python setup build` and `python setup install` and you will get the .egg file in `dist/` folder and the .so file in `build/lib.*` folder. Move them to the knn folder, it works for me

I tried to follow the instruction. With the `python setup build` command I'm getting "RuntimeError: Error compiling objects for extension" error. Any idea how to solve it?

**Comment by yanzhou-li** [comment]
你好，李yanzhou已经收到你的邮件，谢谢！
