### ISSUE TITLE
Generalization Ability of the Method

### ISSUE THREAD

**Issue by eyildiz-ugoe** [j96w/DenseFusion#40]
Hi dear authors,

I was thinking of using the method for kinda small objects (chip, ring, metal pieces, etc. found in devices such as [this)](https://cdn.vox-cdn.com/thumbor/xoa84cZ0gXLF0bCQYBYDuCUyES0=/0x61:1024x744/1200x800/filters:focal(0x61:1024x744)/cdn.vox-cdn.com/assets/801496/seagate-hard-drive.jpg) and wondered if the method could actually generalize, or do we really need to have the precise 3D model of what we are looking for? Because it is impossible to have the models for each and every thing in this domain, so at some point the method should generalize. Would it actually follow this line of thought?

Regards,

**Comment by j96w** [comment]
Hi, this is a good question. However, this work does not cover this part. Actually, another follow up work will come out several months later which will mainly discuss your question. Please wait and see.
