### ISSUE TITLE
RuntimeError: the derivative for 'index' is not implemented.

### ISSUE THREAD

**Issue by qingnanli** [j96w/DenseFusion#41]
I followed @Mars-y470's suggestion and tried to recomplile DenseFusion/lib/knn. The problem #33 'module 'lib.knn.knn_pytorch' has no attribute 'knn'' was solved. 
However, during the YCB training (I ran ./experiments/scripts/train_ycb.sh), I got an error 'RuntimeError: the derivative for 'index' is not implemented'. The details are as follows:

    2019-05-11 22:29:54,240 : Test time 08h 36m 53s Test Frame No.2948 
    dis:0.005122609902173281
    2019-05-11 22:29:54,300 : Test time 08h 36m 53s Epoch 33 TEST FINISH Avg dis: 
    0.01275980792574587
    33 >>>>>>>>----------BEST TEST MODEL SAVED---------<<<<<<<<
    96189
    2949
    >>>>>>>>----------Dataset loaded!---------<<<<<<<<
    length of the training set: 96189
    length of the testing set: 2949
    number of sample points on mesh: 2600
    symmetry object list: [12, 15, 18, 19, 20]
    2019-05-11 22:29:54,795 : Train time 08h 36m 53s, Training started
    Traceback (most recent call last):
      File "./tools/train.py", line 237, in <module>
        main()
      File "./tools/train.py", line 145, in main
        dis, new_points, new_target = criterion_refine(pred_r, pred_t, new_target, model_points, idx, 
    new_points)
      File "/home/qingqing/anaconda3/lib/python3.6/site- 
    packages/torch/nn/modules/module.py", line 489, in __call__
        result = self.forward(*input, **kwargs)
      File "/home/qingqing/Downloads/qingqing_disk/p4600_disk/DenseFusion/lib/loss_refiner.py", 
    line 76, in forward
        return loss_calculation(pred_r, pred_t, target, model_points, idx, points, self.num_pt_mesh, 
    self.sym_list)
      File "/home/qingqing/Downloads/qingqing_disk/p4600_disk/DenseFusion/lib/loss_refiner.py", 
    line 45, in loss_calculation
        target = torch.index_select(target, 1, inds.view(-1) - 1)
    RuntimeError: the derivative for 'index' is not implemented

It seems that the refine process of the network was failed. 
Could you give me some suggestions? @j96w 
Did you meet the same problem? @Mars-y470
Thanks!!

**Comment by huipengly** [comment]
You can change the code in `DenseFusion/lib/loss_refiner.py` line 45.
```python
target = torch.index_select(target, 1, inds.view(-1).detach() - 1)
```
I didn't train refine net, So forgot to change the refine loss code.

**Comment by qingnanli** [comment]
> You can change the code in `DenseFusion/lib/loss_refiner.py` line 45.
> 
> ```python
> target = torch.index_select(target, 1, inds.view(-1).detach() - 1)
> ```
> 
> I didn't train refine net, so forgot to change the refine loss code.

Thank you very much! I will have a try. Now close the issue first.

**Comment by nanfeng-dada** [comment]
@qingnanli  Has this problem been solved? I have also encountered this problem.

**Comment by jity16** [comment]
I modified these two files and it worked. 
~~~python
# lib/loss.py line45
target = torch.index_select(target, 1, inds.view(-1).detach() - 1)
# lib/loss_refiner.py line45
target = torch.index_select(target, 1, inds.view(-1).detach() - 1)
~~~
