### ISSUE TITLE
Undefined symbol error inside knn while training

### ISSUE THREAD

**Issue by Taeuk-Jang** [j96w/DenseFusion#44]
I followed the issue #33 and extracted egg file and moved *so and knn_python.py to the root knn dir.
After that when I run `./experiments/scripts/train_ycb.sh`
it shows the error as below,
`
+ set -e
+ export PYTHONUNBUFFERED=True
+ export CUDA_VISIBLE_DEVICES=0
+ python3 ./tools/train.py --dataset ycb --dataset_root ./datasets/ycb/YCB_Video_Dataset
/home/taeuk/network/DenseFusion/DenseFusion-Pytorch-1.0/lib/transformations.py:1912: UserWarning: failed to import module _transformations
  warnings.warn('failed to import module %s' % name)
Traceback (most recent call last):
  File "./tools/train.py", line 26, in <module>
    from lib.loss import Loss
  File "/home/taeuk/network/DenseFusion/DenseFusion-Pytorch-1.0/lib/loss.py", line 9, in <module>
    from lib.knn.__init__ import KNearestNeighbor
  File "/home/taeuk/network/DenseFusion/DenseFusion-Pytorch-1.0/lib/knn/__init__.py", line 7, in <module>
    from lib.knn import knn_pytorch as knn_pytorch
ImportError: /home/taeuk/network/DenseFusion/DenseFusion-Pytorch-1.0/lib/knn/knn_pytorch.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
`

my system is:
Ubuntu 16.04
GPU : RTX2080 ti
CUDA 10.0
python 3.6.8
pytorch 1.01

any small ideas would be precious for me.
Thanks.

**Comment by Taeuk-Jang** [comment]
if I run with python 0.4.1 and CUDA 9.0
it shows as below:

`
+ set -e
+ export PYTHONUNBUFFERED=True
+ export CUDA_VISIBLE_DEVICES=0
+ CUDA_LAUNCH_BLOCKING=1 python3 ./tools/train.py --dataset ycb --dataset_root ./datasets/ycb/YCB_Video_Dataset
/home/taeuk/network/DenseFusion/DenseFusion/lib/transformations.py:1912: UserWarning: failed to import module _transformations
  warnings.warn('failed to import module %s' % name)
96189
2949
>>>>>>>>----------Dataset loaded!---------<<<<<<<<
length of the training set: 96189
length of the testing set: 2949
number of sample points on mesh: 500
symmetry object list: [12, 15, 18, 19, 20]
/home/taeuk/anaconda3/envs/df/lib/python3.6/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='elementwise_mean' instead.
  warnings.warn(warning.format(ret))
2019-06-03 16:02:25,386 : Train time 00h 00m 00s, Training started
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
/home/taeuk/anaconda3/envs/df/lib/python3.6/site-packages/torch/nn/functional.py:1890: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
/home/taeuk/anaconda3/envs/df/lib/python3.6/site-packages/torch/nn/functional.py:1961: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/home/taeuk/anaconda3/envs/df/lib/python3.6/site-packages/torch/nn/modules/upsampling.py:122: UserWarning: nn.Upsampling is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.Upsampling is deprecated. Use nn.functional.interpolate instead.")
/home/taeuk/anaconda3/envs/df/lib/python3.6/site-packages/torch/nn/modules/container.py:91: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
Traceback (most recent call last):
  File "./tools/train.py", line 237, in <module>
    main()
  File "./tools/train.py", line 140, in main
    loss, dis, new_points, new_target = criterion(pred_r, pred_t, pred_c, target, model_points, idx, points, opt.w, opt.refine_start)
  File "/home/taeuk/anaconda3/envs/df/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/taeuk/network/DenseFusion/DenseFusion/lib/loss.py", line 83, in forward
    return loss_calculation(pred_r, pred_t, pred_c, target, model_points, idx, points, w, refine, self.num_pt_mesh, self.sym_list)
  File "/home/taeuk/network/DenseFusion/DenseFusion/lib/loss.py", line 38, in loss_calculation
    pred = torch.add(torch.bmm(model_points, base), points + pred_t)
RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCBlas.cu:411
`

**Comment by hlcool** [comment]
I have the same question.

**Comment by hygxy** [comment]
Any updates? same problem.

**Comment by hygxy** [comment]
@hlcool  @Taeuk-Jang  The problem may lie on your torchvision version, I followed the suggestion mentioned [here](https://github.com/facebookresearch/maskrcnn-benchmark/issues/223#issuecomment-497991708) and rebuild all .egg and .so files as mentioned [here](https://github.com/j96w/DenseFusion/issues/33#issuecomment-509877511). It works for me
