### ISSUE TITLE
Testing on my own data is not correct

### ISSUE THREAD

**Issue by whuwuh** [j96w/DenseFusion#47]
Thank you very much for sharing the good code, I have run and test the code on YCB data correctly,  I can also draw correct 3d box and point cloud on 2d-image plane. but when I use my own data to test the trained model on YCB, the segmentation result is correct but the pose estimation is not yet, the depth image is stored in png format, uint16, shown as following, could you give me some advice? 
![Predicted_3DBox_0001](https://user-images.githubusercontent.com/50429678/59595578-a8e7e580-9128-11e9-8e5e-7f93253eb3cc.png)
![Predicted_Pose_0001](https://user-images.githubusercontent.com/50429678/59595716-ecdaea80-9128-11e9-8a39-3bb2d99d0c1a.png)
![Normalized_depth_0001](https://user-images.githubusercontent.com/50429678/59595751-ff552400-9128-11e9-892e-90596ae7923e.png)
![Predicted_Label_0001](https://user-images.githubusercontent.com/50429678/59595813-172ca800-9129-11e9-9c8d-7ff76eb44848.png)

**Comment by hoangcuongbk80** [comment]
You are so funny :)) I like your question,  it might be better to test on YCB banana instead of real one.

**Comment by 571502680** [comment]
Can you share your visualization code? If you can, thank you very much.

**Comment by whuwuh** [comment]
I got the right results, the reason may be 1) real banana; 2) depth quality
I just attach correct results on pitch-base here:
![Predicted_3DBox_0001](https://user-images.githubusercontent.com/50429678/60409453-3ed64280-9bf6-11e9-801b-f2879653af00.png)
![Predicted_Pose_0001](https://user-images.githubusercontent.com/50429678/60409459-45fd5080-9bf6-11e9-8577-a6c05a61a474.png)
![Predicted_Label_0001](https://user-images.githubusercontent.com/50429678/60409462-4b5a9b00-9bf6-11e9-9bb4-f3f8915e759d.png)

**Comment by 571502680** [comment]
Can you share your visualization code? If you can, thank you very much.

**Comment by staceycy** [comment]
> I got the right results, the reason may be 1) real banana; 2) depth quality
> I just attach correct results on pitch-base here:
> ![Predicted_3DBox_0001](https://user-images.githubusercontent.com/50429678/60409453-3ed64280-9bf6-11e9-801b-f2879653af00.png)
> ![Predicted_Pose_0001](https://user-images.githubusercontent.com/50429678/60409459-45fd5080-9bf6-11e9-8577-a6c05a61a474.png)
> ![Predicted_Label_0001](https://user-images.githubusercontent.com/50429678/60409462-4b5a9b00-9bf6-11e9-9bb4-f3f8915e759d.png)

Hi @whuwuh , 
Thanks for sharing your results. 
Could you please tell what segmentation model you are using? :)

**Comment by staceycy** [comment]
Hi @whuwuh ,
Thanks for sharing your results.
Could you please tell what segmentation model you are using? :blush:

**Comment by TONG369** [comment]
> Can you share your visualization code? If you can, thank you very much.

I'm also looking for visual code. Can you share your visualization code? If you can, thank you very much.My e-mail address :1563845456@qq.com
