### ISSUE TITLE
how to make my own dataset?

### ISSUE THREAD

**Issue by swjtuccy** [j96w/DenseFusion#48]
Dear sir , i am a freshman in 6d pose , i am tring to learn from your code ,but ,when i need to build my own dataset on a specific object like my own thing  or some other thing .how to make ur own dataset?

**Comment by kaixin-bai** [comment]
https://github.com/NVIDIA/Dataset_Synthesizer

**Comment by kaixin-bai** [comment]
@swjtuccy https://github.com/NVIDIA/Dataset_Synthesizer
https://github.com/zju3dv/pvnet-rendering
maybe these two can help you.

**Comment by liangzhicong456** [comment]
@kaixin-bai Because ycb video model dataset too big, so no download is available. I want to ask about the structure of ycb datset, which data is included. Can the two methods you mentioned get a similar ycb dataset?  Hope for your patient reply,  thanks!

**Comment by ZJU-PLP** [comment]
@kaixin-bai Hi, I have saved the YCB dataset in Baidu pan, you can download in 链接: https://pan.baidu.com/s/1XU2nonhgSVu3aeUc5ovVVA 提取码: cscz

**Comment by j96w** [comment]
> Hi， I have saved the YCB dataset in Baidu pan, you can download in 链接: https://pan.baidu.com/s/1XU2nonhgSVu3aeUc5ovVVA 提取码: cscz

Please make sure you have the admission from [Yu Xiang](https://yuxng.github.io/). A request e-mail should be sent.

**Comment by MrLuer** [comment]
> @swjtuccy [https://github.com/NVIDIA/Dataset_Synthesizer ](https://github.com/NVIDIA/Dataset_Synthesizer)
> https://github.com/zju3dv/pvnet-rendering
> 这两个可能对你有帮助。

how to use this tool? I can't understand
