### ISSUE TITLE
About the update on visualizationcode

### ISSUE THREAD

**Issue by 571502680** [j96w/DenseFusion#52]
Can you share your visualization code? If you can, thank you very much.

**Comment by kaixin-bai** [comment]
there's visualization code in "chainer-dense-fusion" with open3d.

**Comment by 571502680** [comment]
Can you give a link?

**Comment by kaixin-bai** [comment]
https://github.com/knorth55/chainer-dense-fusion
chainer_dense_fusion/visualizations/vis_6d_pose_estimation.py

**Comment by YanqingWu** [comment]
> Can you give a link?


> Can you share your visualization code? If you can, thank you very much.

do you still need the visualization code?

**Comment by TONG369** [comment]
> > Can you give a link?
> 
> > Can you share your visualization code? If you can, thank you very much.
> 
> do you still need the visualization code?

Yes I can,can you give a link?

**Comment by Hanhs-08** [comment]
> > Can you give a link?
> 
> > Can you share your visualization code? If you can, thank you very much.
> 
> do you still need the visualization code?

i need
