### ISSUE TITLE
what is "start_epoch" used for?

### ISSUE THREAD

**Issue by hygxy** [j96w/DenseFusion#53]
Hey, I want to ask what the option "start_epoch" is used for? My understanding is that if the model was trained for example until epoch 42 and the process was terminated, next time it can be set to start from epoch 42 if the option "--start_epoch= 42" is given, is that correct?  

I have observed that the "Avg_dist" is much higher than last time before the process is terminated, e.g.,  the model was trained until 42 epoch and the "Avg_dist" is like 0.00xx before the process is terminated, next time when the process is restarted, it's like 0,0x even if the "--start_epoch=42" is set. Is that normal?

Thanks in advance!

**Comment by j96w** [comment]
Hi, yes, you are correct.
No, that shouldn't happen. Could you run the testing code more times to see whether it is worse?

**Comment by TrinhTUHH** [comment]
If I want to resume from the last checkpoint, how does the command look like?

**Comment by TrinhTUHH** [comment]
@hygxy I got exactly same problem like yours and I don't know how to resume the training.

**Comment by hygxy** [comment]
@j96w  ok, everything is fine, it's my mistake to just pass "start_epoch" and forget the models.
