### ISSUE TITLE
The problem of visualization

### ISSUE THREAD

**Issue by hillaric** [j96w/DenseFusion#54]
when I want to visualize the results of densefusion, I find some errors, could anyone can give some advise?
![image](https://user-images.githubusercontent.com/50513602/60969946-701be480-a353-11e9-9ed1-93df4b3a2d8f.png)

**Comment by ZJU-PLP** [comment]
@hillaric Hi, did you visualize the results by YCB_Video_toolbox? Could you mind telling me the method of your method ? When I use YCB_Video_toolbox to run the matlab code "YCB_Video_toolbox/evaluate
_poses_keyframe.m" and want to use visualize the results, I meet the problem! Thanks a lot in advance!
```
Error using load
Unable to read file 'Densefusion_iterative_result/0026.mat'. No such file or directory.

Error in evaluate_poses_keyframe (line 50)
    result_my = load(filename);
```

**Comment by kaixin-bai** [comment]
seems like that maybe it's because of the false segmentation results.

**Comment by ZJU-PLP** [comment]
@kaixin-bai Hi, did you visualize the results by YCB_Video_toolbox? Could you mind telling me your method? Thanks in advance.

**Comment by kaixin-bai** [comment]
@ZJU-PLP 
https://github.com/j96w/DenseFusion/issues/52
maybe this can help you.

**Comment by ZJU-PLP** [comment]
@kaixin-bai ok,thanks. However, I want to visualize the result by matlab. Did you use #52 method?

**Comment by j96w** [comment]
Yes, it's because of the false segmentation.
