### ISSUE TITLE
problem to run YCB_Video_toolbox/evaluate_poses_ keyframe.m

### ISSUE THREAD

**Issue by ZJU-PLP** [j96w/DenseFusion#55]
Hi, when I use YCB_Video_toolbox to run the matlab code "**YCB_Video_toolbox/evaluate_poses_
keyframe.m**", I meet the problem! Who can help me ? Thanks a lot in advance!
```
Error using load
Unable to read file 'Densefusion_iterative_result/0026.mat'. No such file or directory.

Error in evaluate_poses_keyframe (line 50)
    result_my = load(filename);
```

**Comment by j96w** [comment]
Hi, please make sure whether "0026.mat" is generated. I guess you might have changed the eval code which probably skips some results when the segmentation from PoseCNN fails to find the target object.

**Comment by ZJU-PLP** [comment]
@j96w However, I did not change the eval code? I followed your tips and found only "0025.mat". I could not find the "0026.mat". Can you help me?

**Comment by j96w** [comment]
Hi, it's working well on my side. It would be better to debug from your side. For example, remove the try-except code and see what's going on with index==26.
