### ISSUE TITLE
why is average pooling used?

### ISSUE THREAD

**Issue by kaixin-bai** [j96w/DenseFusion#59]
in the densefusion paper you mentioned "We implement a variant of PointNet architecture that uses **average-pooling** as opposed to the commonly used max-pooling as the symmetric reduction function."

but in pointnet paper figure 5, they have proved that max pooling is better than average pooling and attention sum, so did you do some experiments for the choice of average-pooling? I'm doing something with pointnet now, and i'm confused with this part. thanks a lot!

**Comment by j96w** [comment]
Please refer to [Issue#34](https://github.com/j96w/DenseFusion/issues/34).
