### ISSUE TITLE
Fail to use show_pose_result.m to see the alignment of Segmentation and Transformation

### ISSUE THREAD

**Issue by MaxChanger** [j96w/DenseFusion#61]
Hello, I am currently trying to use your code in the YCB dataset. As you say in readme.md, I run `./experiments/scripts/eval_ycb.sh` to acquire the result, and then copy them to YCB_Video_toolbox, using `***.m` to compare the result between DenseFusion and PoseCNN.

But I also want to generate the picture of qualitative result  in your paper and readme.md, so I use `show_pose_results.m` to generate the picture, I have some trouble in this step.

At first, this file is designed for PoseCNN, I think you don't modify it to DenseFusion, **I find there is no `result.rois` item in DenseFusion's result, as the following picture shown.**

I can run this code used PoseCNN's Result, but not in DenseFusion.
Could you tell how to deal with this problem, thanks.

![2019-07-27 21-40-25屏幕截图](https://user-images.githubusercontent.com/35401968/61995548-8ef0d980-b0bc-11e9-9152-de98baf20f4a.png)
![right](https://user-images.githubusercontent.com/35401968/61995622-5c93ac00-b0bd-11e9-91cd-0c23d08e6839.jpg)

**Comment by j96w** [comment]
Hi, 
The modified `evaluate_poses_keyframe.m` and `plot_accuracy_keyframe.m` I provide are only used to get the quantitative evaluation on YCB dataset. To get the qualitative results, you might need to write some lines of code according to your needs. Simply, you can transform the object model point cloud with the predicted pose and back project each point to the 2d image to get the result I show in the paper.

**Comment by MaxChanger** [comment]
Thanks for your reply, if so, could you tell me the specific representations of individual `001.mat` or `002.mat` in the `Densefusion_iterative_result` or `Densefusion_wo_refine_result`,  what does the term of this 5*7 matrix mean? So that I can write some code to accomplish this task. 
Thanks.

**Comment by j96w** [comment]
Hi, 5 means there are 5 objects in this frame. 7 means quaternion(4)+translation(3) for each object.

**Comment by MaxChanger** [comment]
Thanks for you reply, I hope I can accomplish this task.
