### ISSUE TITLE
about gt.yml file

### ISSUE THREAD

**Issue by hygxy** [j96w/DenseFusion#62]
Hey, I was trying to create  my own dataset and came across a small question regarding the gt.yml file. I tried with the follwoing line to read from the gt.yaml file : 
- gt_file = open('gt.yml')
- gt = yaml.load(gt_file, Loader= yaml.FullLoader)
- print(gt)

and got something like this:

{0: [{'cam_R_m2c': [0.0963063, 0.99404401, 0.0510079, 0.57332098, -0.0135081, -0.81922001, -0.81365103, 0.10814, -0.57120699], 'cam_t_m2c': [-105.3577515, -117.52119142, 1014.8770132], 'obj_bb': [244, 150, 44, 58], 'obj_id': 1}], 1: [{'cam_R_m2c': [0.113309, 0.99136102, 0.0660649, 0.58543199, -0.0128929, -0.810619, -0.802764, 0.130527, -0.58183599], 'cam_t_m2c': [-123.75479622, -117.18555277, 1020.10820079], 'obj_bb': [234, 151, 44, 58], 'obj_id': 1}], ...}

but when i tried to write the same content(just two rank) back to another .yaml file with the following:
- data = {0: [{'cam_R_m2c': 
            [0.0963063, 0.99404401, 0.0510079, 0.57332098, -0.0135081, -0.81922001, -0.81365103, 0.10814, -0.57120699], 
            'cam_t_m2c': 
            [-105.3577515, -117.52119142, 1014.8770132], 
            'obj_bb': 
            [244, 150, 44, 58], 
            'obj_id': 1}],
        1: [{'cam_R_m2c': 
            [0.113309, 0.99136102, 0.0660649, 0.58543199, -0.0128929, -0.810619, -0.802764, 0.130527, -0.58183599], 
             'cam_t_m2c': [-123.75479622, -117.18555277, 1020.10820079], 
             'obj_bb': [234, 151, 44, 58], 
             'obj_id': 1}] } 
- with io.open('data.yml', 'w' ) as outfile:
    yaml.dump(data, outfile, default_flow_style=False)

I got the following:
![my](https://user-images.githubusercontent.com/28361684/62009532-9b2e7280-b160-11e9-96eb-fb428a19dcab.png)

So here is my question: how did you create the gt.ymal file with the format like following:
![their](https://user-images.githubusercontent.com/28361684/62009546-cadd7a80-b160-11e9-9b0c-ff7c14ad3ac3.png)

Thanks in advance!

**Comment by mateoKutnjak** [comment]
I also got format like you did, but it does not matter when you read .yaml file with python yaml library. If you want the script to look like theirs write a script for reformatting .yaml file, but like I said it is not necessary.

**Comment by j96w** [comment]
Hi, @mateoKutnjak is right.
