### ISSUE TITLE
Reference to non-existent field 'model_path'

### ISSUE THREAD

**Issue by yanzhou-li** [j96w/DenseFusion#63]
Thank you so much for sharing! now I have a problem.
when I run the code "show_pose_results.m",it will be reported the error:Reference to non-existent field 'model_path'.
As follows:
show_pose_results
loading 3D models...
Reference to non-existent field 'model_path'.
Error in show_pose_results (line 23)
file_obj = fullfile(opt.model_path, object_names{i}, 'textured.obj');
can you tell me what's that means.and how to get it works,thanks.

**Comment by chenjiale5** [comment]
I meet the same problem, have you solved it?

**Comment by yanzhou-li** [comment]
> I meet the same problem, have you solved it?

Try to replace "opt.model_path" with "opt.root", it seems to work for me .Good luck

**Comment by j96w** [comment]
It seems like a folder address issue. Could you double check the loading step in your code?
