### ISSUE TITLE
Is it possible that I can get trained weights of vanilla SegNet?

### ISSUE THREAD

**Issue by gusye1234** [j96w/DenseFusion#64]
Hi, I'm trying to run this model on my laptop.
It's so generous that the authors share their trained checkpoints. However, I notice that there are no trained weights of vanilla SegNet in the checkpoints.
Is it possible that I can get trained weights of vanilla SegNet?
Thanks!

**Comment by j96w** [comment]
Hi, there is no strict choice on the segmentation model. You can choose the one according to your training platform and needs.

**Comment by huckl3b3rry87** [comment]
@j96w I know that there is no strict choice, but do you mind providing these weights? It would save me some time...I already created a pull request that adds Docker and am working to include ros
