### ISSUE TITLE
How long will it take to train DenseFusion?

### ISSUE THREAD

**Issue by poodarchu** [j96w/DenseFusion#65]

**Comment by TrinhTUHH** [comment]
after 70 epochs, I got like 95% of accuracy on the evaluation.

**Comment by poodarchu** [comment]
> after 70 epochs, I got like 95% of accuracy on the evaluation.

Thanks, but I'm asking for training time, could you please provide that?

**Comment by TrinhTUHH** [comment]
One and a half day I guess

**Comment by poodarchu** [comment]
> One and a half day I guess

guess?

**Comment by WW-0** [comment]
I have the same question！When I used a 1080TI GPU for training, 2G video memory was occupied, and each epoch lasted about 40 minutes。What equipment does the author use ？ How long will it take to train DenseFusion?
