### ISSUE TITLE
RuntimeError: the derivative for 'index' is not implemented

### ISSUE THREAD

**Issue by nanfeng-dada** [j96w/DenseFusion#67]
I encountered this problem in training my own data. The object model is symmetrical, and this error(like #41) occurs when refinenet is used.But #41 did not give a a soultion

**Comment by hygxy** [comment]
@nanfeng-dada [41](https://github.com/j96w/DenseFusion/issues/41) does give a solution: 
inds.view(-1) ---->inds.view(-1).detach()

adding detach() will solve hopefully solve your problem.

**Comment by nanfeng-dada** [comment]
@hygxy it works and thank you so much,it is my mistake that I didn't notice the code changes.
