### ISSUE TITLE
The different mask's pixel values of the Linemod_processed dataset are more the classes.

### ISSUE THREAD

**Issue by gusye1234** [j96w/DenseFusion#68]
Hi, I'm trying to train vanilla segment on the Linemod_processed dataset, which means I need to write a new data_controller file.
However, I notice that only *02* folder of the Linemod_processed dataset has the mask of all the object, other folders only have one object's mask.
Furthermore, I found out that there are more than 16 classes of pixel values in the *02* folder ...  
In fact, the values are 
```
[0, 21, 23, 26, 43, 46, 51, 106, 116, 128, 139, 153, 170, 185, 191, 204, 209, 213, 230, 232, 234, 255]
```
whose classes is 22.
I'm a little bit confused, cause there are only 15 objects are given in the Linemoe_processed dataset, not including background class.
So, how am I supposed to handle 22 different pixel values, are there some pixel values meaningless that don't represent any class?
Thanks

the code I count the pixel values is below:
```python
for i in os.listdir("mask_all"):
    a = np.array(Image.open("mask_all/" + i))
    a = np.unique(a)
    for i in a:
        if i in b:
            pass
        else:
            b.append(i)
```

**Comment by TrinhTUHH** [comment]
@gusye1234 Hi, I am doing the same. I have a question, in the mask images of Linemod do we need to replac object pixels (with value of 255) by rank/order of the class, just like in ycb dataset?

**Comment by TrinhTUHH** [comment]
Most of the images have total 9 values for pixel. Only 4 or 5 images have different pixel values, athough objects are the same. You can check by print out unique values from all images, then print out name of images which have less common pixel values (one example is 0566.png). 
Do you know did they preprocess the data to get the mask-all and the ground truth transformation for all objects? The original data does not provide this I guess.

**Comment by j96w** [comment]
Hi, actually this "Linemod_processed dataset" is adapted from "the preprocessed LINEMOD dataset" from https://github.com/microsoft/singleshotpose. At the beginning, I'm also confused by the 02 folder. But since I only need the mask of object 02, so I just extract this mask and use it. The mask I get is by transforming the mesh with the GT pose to the 3D scene then back-project it to the image plane and get the contour as the mask.
