### ISSUE TITLE
Detection of real objects

### ISSUE THREAD

**Issue by Sunweijun333** [j96w/DenseFusion#70]
Can this project be used directly to detect real objects in LINEMOD or YCB-video in real time? Thank you for your reply.

**Comment by j96w** [comment]
Hi, yes it can. You can refer to our paper Table 3 for more information about the inference speed.

**Comment by TONG369** [comment]
> Hi, yes it can. You can refer to our paper Table 3 for more information about the inference speed.


The  code for directly to detect real objects in LINEMOD or YCB-video in real time is  open source? Can you share it? Or a link to a reference. Looking forward to your reply !!!
