### ISSUE TITLE
YCB dataset

### ISSUE THREAD

**Issue by sanjaysswami** [j96w/DenseFusion#71]
Hello,
I am trying to visualize LineMOD output using chainer-dense-fusion. But unfortunately chainer-dense-fusion is written for ycb dataset. I am trying to understand the code but i do not have ycb datset and as it is very big i do not have enough space to download it. **Just to understand what {index}-meta.mat conatins, rather how values have said in it, can anyone provide me few {index}-meta.mat files if anyone has downloaded ycb dataset.** 

I would be very greatful if someone can provide me {index}-meta.mat .
Thank you.

**Comment by hygxy** [comment]
@sanjaysswami  take a look at this [link](https://github.com/Abdul-Mukit/ycb_video_data_share)

**Comment by sanjaysswami** [comment]
@hygxy Thank you...
