### ISSUE TITLE
Invalid Uncertainty Prediction

### ISSUE THREAD

**Issue by WilliamKRobert** [j96w/DenseFusion#74]
It looks like the model does not learn the uncertainty well. Using the provided pretrained model, I got the same results as listed in the paper, but I use the point with lowest uncertainty. Which means, the predicted uncertainty does not help at all.

Any idea?

**Comment by j96w** [comment]
Hi, did you open the iterative refinement step? To see the uncertainty performance, we need to turn it off and only check the "per-pixel" results.
