### ISSUE TITLE
Question about symmetric loss

### ISSUE THREAD

**Issue by ghavidelsahar** [j96w/DenseFusion#77]
I have a question about symmetric loss:
https://github.com/j96w/DenseFusion/blob/584efd68810c4d2f818207f2719a6ae886aac825/lib/loss.py#L44
when KNN returns the inds, they are mostly duplicated (for instance, I have a symmetric object with 500 object points. Using symmetric loss these 500 points get compared with only 30 selected points in the target tensor. In other words, we only have 30 unique indices in inds tensor). Is this something you expect?

Thanks

**Comment by j96w** [comment]
Hi, does your case happen at the beginning of the training or in the end? I guess it's during the beginning when the 3D IoU between your prediction and GT is too large to match with most points on the model.
