### ISSUE TITLE
Ask about quaternion_matrix function

### ISSUE THREAD

**Issue by TrinhTUHH** [j96w/DenseFusion#78]
When using the quaternion_matrix function I notice that the result is not as expected. For example,  running `quaternion_matrix([0.99810947, 0.06146124, 0, 0])` I got:
[[ 1.          0.          0.          0.        ]
 [ 0.          0.99244503 -0.12269009  0.        ]
 [ 0.          0.12269009  0.99244503  0.        ]
 [ 0.          0.          0.          1.        ]]

but in fact, the rotation matrix should be
[  0.9924451,  0.1226901,  0.0000000;
   0.1226901, -0.9924451,  0.0000000;
   0.0000000,  0.0000000, -1.0000000 ]

Is the function incorrect or I understand it wrong?

**Comment by hygxy** [comment]
@TrinhTUHH  Hey, did you figure out why?

**Comment by TrinhTUHH** [comment]
Yes, the arguments in quaternion_matrix() function is: x,y,z,w but I thought it is w,x,y,z. That's why.
