### ISSUE TITLE
How to generate ground truth for dataset?

### ISSUE THREAD

**Issue by sanjaysswami** [j96w/DenseFusion#79]
**#creator** of **#LineMOD_dataset** has used kinect camera to capture the photos and depth information which I can understand. But I am wondering how he has generated/obtained following things:

1. How he has generated rotational and translation matrices for an particular object in corresponding images?
2. How he has generated mesh.ply file for each object? which method he might have used?
3. If you see **#Linemod_preprocessed dataset** he has provided:
        a) gt.yml file containing R and T matrices and additionally Bounding Box co-ordinates. I
            am again wondering how he has generated this information which he has used in dense
            fusion algorithm
        b) Mask folder containing mask.png for perticular object in each single image. Again if he
            has taken images from kinect camera then how he has generated mask for each image.

**Comment by MrLuer** [comment]
I want to make my own dataset and have the same issues，do you get  any solution？

**Comment by sanjaysswami** [comment]
@MrLuer I have not received answers and I am still trying to figure it out.

**Comment by MrLuer** [comment]
@sanjaysswami the NDDS said to can  label 3D images，but I don't konw how to use it
https://github.com/NVIDIA/Dataset_Synthesizer

**Comment by j96w** [comment]
Hi, for me, SIXD_toolkit works the best.

**Comment by satpalsr** [comment]
Hey @sanjaysswami @MrLuer @j96w , I have a custom dataset with RGB images, masked images & the 3Dmodel.ply. I wonder if you found some way to get R (3x3 cam_R_m2c - model to camera co-ord system)& T (3x1 cam_T_m2c -model to camera co-ord system) matrices?
