### ISSUE TITLE
Size estimation

### ISSUE THREAD

**Issue by lorenzograziano** [j96w/DenseFusion#81]
Given that during the training phase the 3d model of the object is used to minimize the cost function, it is possible that the architecture can correctly infer the 6d pose of the same object with a different size? 

I am wondering if can be possible to estimate the size of the object before the inference in order to use this additional information in order to improve the estimation of different instances of the same object.

**Comment by j96w** [comment]
Hi, I agree this could be an improvement idea. Maybe we can use the geometry embedding extraction branch to predict the scale of the object first, then normalize the input cloud into the predicted scale. This might have the potential to handle same object with different size.
