### ISSUE TITLE
depth scale in ycb

### ISSUE THREAD

**Issue by sanjaysswami** [j96w/DenseFusion#82]
@j96w in linemod dataset.py 
cam_scale = 1.0                                         
pt2 = depth_masked / cam_scale
pt0 = (ymap_masked - self.cam_cx) * pt2 / self.cam_fx
pt1 = (xmap_masked - self.cam_cy) * pt2 / self.cam_fy
cloud = np.concatenate((pt0, pt1, pt2), axis=1)
cloud = np.add(cloud, -1.0 * target_t) / 1000.0
you have divided by factor 1000 to convert mm to meter.

now in ycb dataset.py you have changed this scaling factor to 10000.0
I am not understanding this logic. Can you please give me the reason.
(I have checked maximum value of few depth images from available on [this](https://github.com/Abdul-Mukit/ycb_video_data_share). For 000000-depth.png it is 12190. For 000004-depth.png it is 12885.)

**Comment by j96w** [comment]
Hi, actually, I didn't get your point. Do you have some trouble to project the cloud to the image with the camera intrinsic I use or you found the generated point cloud is not its reasonable size?

For YCB, the scale of the camera is provided by the dataset. https://github.com/j96w/DenseFusion/blob/4cd82f4f68025244982f03eaa3cfd5efd9d99ef5/datasets/ycb/dataset.py#L191

For Linemod, the original metric is in mm. To convert the cloud to meter, camera scale is set to 1000.
