### ISSUE TITLE
Multi branches to produce R, T, C separatly

### ISSUE THREAD

**Issue by zeal-github** [j96w/DenseFusion#83]
Hi, thanks for sharing your project.
I have some question about the output layer of PoseNet.
```
        self.conv1_r = torch.nn.Conv1d(1408, 640, 1)
        self.conv1_t = torch.nn.Conv1d(1408, 640, 1)
        self.conv1_c = torch.nn.Conv1d(1408, 640, 1)

        self.conv2_r = torch.nn.Conv1d(640, 256, 1)
        self.conv2_t = torch.nn.Conv1d(640, 256, 1)
        self.conv2_c = torch.nn.Conv1d(640, 256, 1)

        self.conv3_r = torch.nn.Conv1d(256, 128, 1)
        self.conv3_t = torch.nn.Conv1d(256, 128, 1)
        self.conv3_c = torch.nn.Conv1d(256, 128, 1)

        self.conv4_r = torch.nn.Conv1d(128, num_obj*4, 1) #quaternion
        self.conv4_t = torch.nn.Conv1d(128, num_obj*3, 1) #translation
        self.conv4_c = torch.nn.Conv1d(128, num_obj*1, 1) #confidence

        self.num_obj = num_obj
```
1. you use three branches to produce r, t, c separatly, I think it can be done in one branch but with different output channels. Does using three branches affect the performance obviously?

2. why do you use one output channel for each obj(num_obj*4/3/1) separately.  Why can't we use one output channel for all obj? I think it reasonable both theoretically and technically.

**Comment by j96w** [comment]
Ya, they are fundamentally the same. You can do that.
