### ISSUE TITLE
Training on other datasets

### ISSUE THREAD

**Issue by Allen3C** [j96w/DenseFusion#85]
Hello,thanks for sharing your project!
I had a problem training other datasets.
![Screenshot from 2019-09-17 17-18-14](https://user-images.githubusercontent.com/54675192/65029113-bacb6580-d96f-11e9-9855-7e3a8db0fae9.png)
It took some time to train before the mistake occurred，I can't find out which part of the input went wrong.

What's your advice？ thank you！

**Comment by j96w** [comment]
Hi, it seems like the format of the input RGB is not correct. Could you try to figure out what is current wrong format? Maybe there is some data that is broken or something like that?

**Comment by KatharinaSchmidt** [comment]
I have the same issue with my custom dataset. @Allen3C , can you tell me, how you solved it? Did you recreate a new dataset or changed some lines in the code?

**Comment by bophancong** [comment]
KatharinaSchmidt

> I have the same issue with my custom dataset. @Allen3C , can you tell me, how you solved it? Did you recreate a new dataset or changed some lines in the code?

You had a same problem with you. I found the solution in this post #98 . You can check it out.

**Comment by KatharinaSchmidt** [comment]
Thank you for that hint.
