### ISSUE TITLE
about inference

### ISSUE THREAD

**Issue by YanqingWu** [j96w/DenseFusion#89]
when training, we feed the cropped image, test also. 
Now, i want to inference a new image :
should I first use the segnet to get the segment;
then feed the cropped image to get the predicts, just like train or test;
then project the predicts to the origin image for visualization.
Am I right?
thanks for your patience.

**Comment by j96w** [comment]
Hi, yes, you are right. To have a higher inference speed, the projection step can be delayed to after-process for visualization.

**Comment by an99990** [comment]
hi @YanqingWu , do you have a working example in which you do inference with DenseFusion ?
I am having trouble understanding the arguments for the estimator, in case of linemod
`estimator(img, points, choose, idx)`
img is the image, points is the point cloud, but what is choose ? and idx ? what are those two arguments in case of real time settings ? I have segmentation mask coming from another model, which argument would that be ?

thank you so much for any help
