### ISSUE TITLE
What are the differences between the original LINEMOD Dataset and the provided Processed one ?

### ISSUE THREAD

**Issue by bringBackm** [j96w/DenseFusion#9]
l notice the two .yml files, where they come from? 
And is there any other difference..?
Thank You!

**Comment by j96w** [comment]
The provided processed LINEMOD contains additional ground truth segmentation masks, which are generated by the projecting the object mesh with gt pose to the camera frame. 'gt.yml' is the gt pose. 'info.yml' is the camera information. These .yml files are borrowed and reassembled from https://github.com/Microsoft/singleshotpose.

**Comment by j96w** [comment]
The provided processed LINEMOD contains additional ground truth segmentation masks, which are generated by projecting the object mesh with gt pose to the camera frame. 'gt.yml' is the gt pose. 'info.yml' is the camera information. These .yml files are borrowed and reassembled from https://github.com/Microsoft/singleshotpose.

**Comment by bringBackm** [comment]
Thanks for replying

**Comment by zeal-github** [comment]
@j96w Hi, I notice that the LINEMOD dataset release in this repo seems different from the https://github.com/Microsoft/singleshotpose. The 3D models are not registered and the length unit it's also different(m & mm).

**Comment by MrLuer** [comment]
> 提供的处理过的LINEMOD包含附加的地面实况分割掩模，其通过将具有gt姿势的对象网格投影到相机帧来生成。'gt.yml'是gt姿势。'info.yml'是相机信息。这些.yml的英文文件从https://github.com/Microsoft/singleshotpose借用并重新组装的。



> The provided processed LINEMOD contains additional ground truth segmentation masks, which are generated by projecting the object mesh with gt pose to the camera frame. 'gt.yml' is the gt pose. 'info.yml' is the camera information. These .yml files are borrowed and reassembled from https://github.com/Microsoft/singleshotpose.
this link provides the 3D info made of 21  dimension  ，but how it transform to R and T matrix in gt.yml?

**Comment by MrLuer** [comment]
> The provided processed LINEMOD contains additional ground truth segmentation masks, which are generated by projecting the object mesh with gt pose to the camera frame. 'gt.yml' is the gt pose. 'info.yml' is the camera information. These .yml files are borrowed and reassembled from https://github.com/Microsoft/singleshotpose.

this link provides the 3D info made of 21 dimension ，but how it transform to R and T matrix in gt.yml?
thank you
