### ISSUE TITLE
how to generation cam_R_m2c and cam_t_m2c 

### ISSUE THREAD

**Issue by MrLuer** [j96w/DenseFusion#90]
first，thank you for your share.
I attempt to create my own linemod dataset， I have generation data follow the  https://github.com/microsoft/singleshotpose ，but I dont know how to transform it to densefusion format，how the 21 dimensional data transform to cam_R_m2c and cam_t_m2c  in gt.yml?

你好像是中国人，因此我再用中文说一次吧，我想要训练自己的数据集，我生成了和这个链接https://github.com/microsoft/singleshotpose 的linemod 一样的数据，但是我不知道怎样将他转换成为Densefusion能用的格式，我所生成的21维数据如何转换成gt.yml 文件中的cam_R_m2c 和 cam_t_m2c？（cam_R_m2c 和 cam_t_m2c旋转和平移矩阵吧？）。
 非常感谢代码分享，如果能解答我的疑问我将不甚感激。 @j96w

**Comment by j96w** [comment]
Hi, `cam_R_m2c` here refers to the 3\*3 orientation matrix and `cam_t_m2c` is the 1\*3 translation. If you have questions about the format of the data generated by Yolo6D, it would be better to ask them.

**Comment by danikhani** [comment]
Hello @MrLuer,

did you find an answer for your question? Would be great if you could share it here
Thank you!

**Comment by MrLuer** [comment]
> Hello @MrLuer,
> 
> did you find an answer for your question? Would be great if you could share it here
> Thank you!

I'm fraid I have nothing offer to you cause it's a very old work for me, I can't remember some valueable information

**Comment by Jiang-Zhen-Hong** [comment]
> Hi, `cam_R_m2c` here refers to the 3*3 orientation matrix and `cam_t_m2c` is the 1*3 translation. If you have questions about the format of the data generated by Yolo6D, it would be better to ask them.
Hi! Does' cam_R_m2c 'represent the transformation of the object coordinate system to the camera coordinate system or the transformation of the camera coordinate system to the object coordinate system?
