### ISSUE TITLE
question about generate the cloud

### ISSUE THREAD

**Issue by YanqingWu** [j96w/DenseFusion#92]
cloud = np.concatenate((pt0, pt1, pt2), axis=1)
cloud = np.add(cloud, -1.0 * target_t) / 1000.0
cloud = np.add(cloud, target_t / 1000.0)

I don't understand why generate the cloud need the target_t ?
because during the inference, we haven't the target_t, that's it.

**Comment by j96w** [comment]
Hi, actually these two lines of code equal to `cloud = cloud / 1000.0`. So the target_t here doesn't have an effect. I have made a new update to the code. Please take a look.

**Comment by YanqingWu** [comment]
@j96w I think you can update the pytorch-1.0, too.
