### ISSUE TITLE
where is the setup.py in knn? don't konw how to build it now

### ISSUE THREAD

**Issue by 704051419** [j96w/DenseFusion#93]
when run the train program ,it says
`    from ._knn_pytorch import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'lib.knn.knn_pytorch._knn_pytorch'`

but now how to rebuild it now?

**Comment by 704051419** [comment]
i use make to complile, then:
`python3 build_ffi.py
process_begin: CreateProcess(NULL, python3 build_ffi.py, ...) failed.
make (e=2):
Makefile:31: recipe for target 'build/knn_pytorch/_knn_pytorch.so' failed
make: *** [build/knn_pytorch/_knn_pytorch.so] Error 2
`

**Comment by j96w** [comment]
Hi, actually I am considering to change the knn module here but I probably need more time to clear what I'm working on then go back to this. Currently, you might find some help from https://github.com/chrischoy/pytorch_knn_cuda.
