### ISSUE TITLE
Simple inference example

### ISSUE THREAD

**Issue by amodas** [j96w/DenseFusion#94]
Hello! Thanks for the nice work!

I am quite new to the whole domain and I am struggling to run a very simple experiment.

Let's say that I have the following data:
1. An RGB image
2. The corresponding depth image
3. The segmentation mask for the object of interest

How could I simply feed the data to the network and get the 6D pose estimation? I am reading the eval_ycb.py (also the eval_linemod), but I cannot understand how to properly use the network. It seems that it requires some inputs that I do not know how to generate...

Is there a simple working example that, given some RGB-D + seg_mask data, the model estimates the 6D pose?

Thank you in advance,
Apostolos

**Comment by Rajat-Mehta** [comment]
@amodas did you figure out the solution to your question?

**Comment by an99990** [comment]
@amodas @Rajat-Mehta anyone got a simple example ?

**Comment by amodas** [comment]
Unfortunately, no. I dropped the effort.
