### ISSUE TITLE
When I run EvalLinemod, I get an error like the following.

### ISSUE THREAD

**Issue by bbg-pjg** [j96w/DenseFusion#95]
`No.7163 Pass! Distance: 0.00671278461486
No.7164 Pass! Distance: 0.00488601767201
No.7165 Pass! Distance: 0.0029793963296
No.7166 Pass! Distance: 0.00561164342838
No.7167 Pass! Distance: 0.0094630294294
No.7168 Pass! Distance: 0.00634427591226
No.7169 Pass! Distance: 0.00561537606658
No.7170 Pass! Distance: 0.00607852813929
No.7171 Pass! Distance: 0.00574784192298
No.7172 Pass! Distance: 0.00446096530503
No.7173 Pass! Distance: 0.00781700340443
No.7174 Pass! Distance: 0.00747477354172
No.7175 Pass! Distance: 0.00591208421742
No.7176 Pass! Distance: 0.00575960512164
No.7177 Pass! Distance: 0.0038485964787
No.7178 Pass! Distance: 0.00323641426211
No.7179 Pass! Distance: 0.00568495947719
No.7180 Pass! Distance: 0.00462880319079
No.7181 Pass! Distance: 0.00717002703232
No.7182 Pass! Distance: 0.00190642736425
No.7183 Pass! Distance: 0.00377156909408
No.7184 Pass! Distance: 0.00747363441321
No.7185 Pass! Distance: 0.00427901386164
No.7186 Pass! Distance: 0.00973293344599
No.7187 Pass! Distance: 0.0106931742672
No.7188 NOT Pass! Distance: 0.011297486951
No.7189 Pass! Distance: 0.00641312204752
No.7190 NOT Pass! Distance: 0.0152984733666
No.7191 NOT Pass! Distance: 0.0372263327895
No.7192 NOT Pass! Distance: 0.0118271590556
Traceback (most recent call last):
  File "./tools/eval_linemod.py", line 126, in <module>
    inds = knn(target.unsqueeze(0), pred.unsqueeze(0))
  File "/home/user/SWJ/DenseFusion/lib/knn/__init__.py", line 21, in forward
    knn_pytorch.knn(ref, query, inds, dists)
  File "/home/user/anaconda3/envs/swj-densepose/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 202, in safe_call
    result = torch._C._safe_call(*args, **kwargs)
torch.FatalError: invalid argument 0: ref_tensor: 2D Tensor expected at /home/user/SWJ/DenseFusion/lib/knn/src/knn_pytorch.c:11
`

**Comment by j96w** [comment]
Hi, sorry, I think this problem is beyond my scope. Any more information?

**Comment by bbg-pjg** [comment]
OK, Thank you!
