### ISSUE TITLE
Troubles with own synthetic dataset

### ISSUE THREAD

**Issue by marmas92** [j96w/DenseFusion#98]
First of all thank you for sharing your code!
I try to train with my own sythetic generated dataset (same format as the preprocessed linemod dataset), but the following error occures:
"RuntimeError: Expected 4-dimensional input for 4-dimensional weight 64 3, but got 2-dimensional input of size [1, 1] instead" 
Attached I have my generated data. Could someone please tell me what I did wrong and how to fix it? Thank you very much in advance!!

![0000](https://user-images.githubusercontent.com/51153981/66853020-9ff40d00-ef7e-11e9-8281-288808332d22.png)
![0000](https://user-images.githubusercontent.com/51153981/66853023-a2eefd80-ef7e-11e9-8f62-335bd6297443.png)
![0000](https://user-images.githubusercontent.com/51153981/66853033-a5e9ee00-ef7e-11e9-81b9-3c357cc3f26a.png)

**Comment by StrawnSC** [comment]
Hello! I am getting the same error with our custom data set as well. If you find a fix, could you please let me know? 
Thanks!

**Comment by marmas92** [comment]
I solved the problem: I generated the wrong boundingboxcoordinates. 
I wrote the coordinates down like this -> obj_bb: [maxX, maxY, minX, minY]
But actually the coordinates need to be give like -> obj_bb: [minX, minY, widhtOfBbx, heigthOfBbx]

**Comment by StrawnSC** [comment]
Our problem turned out to be with our image generation. That error seems to happen when the bounding box drawn in the image doesn't contain the object.

**Comment by v-wewei** [comment]
> sythetic generated

hi, how did you sythtic your own dataset ? 
Thanks very much !

**Comment by marmas92** [comment]
I used Unity and randomly generate objects with a random rotation and translation into the scene. After that you need to extract the necessary information.

**Comment by Windson9** [comment]
Hi @marmas92. Can you please share if you were you able to achieve good results with your own data ?
